### ISSUE TITLE
Installed extension but nothing happens

### ISSUE THREAD

**Issue by rm-rf-etc** [refined-bitbucket/refined-bitbucket#102]
At first I could not figure out how to make this extension work. I tried several things before deciding to logout of bitbucket and log back in. There's no mention, in the readme, of the need to do this. I think this needs to be added to the [_Installing_ section](https://github.com/refined-bitbucket/refined-bitbucket#installing). Currently it says only "refined-bitbucket is available on the Google Chrome Web Store.", not especially helpful.

**Comment by reyronald** [comment]
Hello! 

Did it work when you logged out and then logged in?

Honestly I don't remember having this issue myself when I first installed it. I'm thinking that maybe it's a cache related problem with Chrome that doesn't happen to everyone all the time.

Regardless, I'll try to see if I can reproduce it and will definitely add the suggestion to the readme, like you said.

Thank you for bringing it up!

**Comment by rm-rf-etc** [comment]
Hi Ronald, yes, that solved the issue. Thanks so much for your efforts.

**Comment by reyronald** [comment]
No problem Rob! Hope you enjoy the extension. Let me know if you find any other issue :)
