### ISSUE TITLE
[FR] Pull request template

### ISSUE THREAD

**Issue by fawques** [refined-bitbucket/refined-bitbucket#105]
Hi, could you implement pull request templates? The [corresponding bitbucket feature request](https://bitbucket.org/site/master/issues/11571/custom-pull-request-description-template) has > 200 votes but almost no response from the atlassian team.

I found a [chrome extension](https://github.com/tcrammond/chrome-pullrequest-templates) that does this, but not a firefox one.

This is related to  #97

**Comment by reyronald** [comment]
Hey @vguzmanp , take a look at the description of #106, is that how you would expect it to work ?

I coded it to mimic the GitHub functionality since some users might already be used to that.

**Comment by fawques** [comment]
Hi @reyronald, thank you for doing it so quickly!
Yes, mimicking the github behavior is the best way to go.

It would also be super useful to be able to set an external URL to fetch the template, so that I can use the same template in different repositories, but with the current PR I'm already happy :)

**Comment by reyronald** [comment]
Closed via #106, and already available in the [released v3.4.0](https://github.com/refined-bitbucket/refined-bitbucket/releases/tag/v3.4.0).

@vguzmanp Let me know how if it's working for you or if you have any feedback!
