### ISSUE TITLE
Manifest file is invalid

### ISSUE THREAD

**Issue by arhughes** [refined-bitbucket/refined-bitbucket#117]
Installing from the Chrome Web Store fails with a "Manifest file is invalid." error message.

**Comment by reyronald** [comment]
Hmm, that's odd, I just reinstalled and don't see the error message, also @burntcookie90 reported here https://github.com/refined-bitbucket/refined-bitbucket/issues/96#issuecomment-359925975 that he could update properly as well.

Can you uninstall and reinstall, close and reopen Chrome or anything similar to check?

**Comment by arhughes** [comment]
Just tried again without doing anything else and it worked fine.

**Comment by reyronald** [comment]
We've had similar troubles with Chrome / the web store before (see #102), seems like Google has some polishing to do on it.

Glad to know it was false alarm!
