### ISSUE TITLE
Missing few template engine support

### ISSUE THREAD

**Issue by lacrm** [refined-bitbucket/refined-bitbucket#121]
Hey nice extension, i see that there is no support for the smarty template files (*.tpl) or the (*.twig) template with your extension. It would be nice to find it in an upcoming update, thanks.

**Comment by reyronald** [comment]
Hello @lacrm !

I think the name of the classes for those languages should be `language-smarty` and `language-twig` respectively.

Do you have by any chance have a link to a public Bitbucket repository that has files in this format so that I can test it? Or are you willing test it yourself?

**Comment by reyronald** [comment]
Closed via #123
