### ISSUE TITLE
Syntax Highlighting doesn't work

### ISSUE THREAD

**Issue by dpekkle** [refined-bitbucket/refined-bitbucket#143]
Hi, I've just set this up but Syntax Highlighting doesn't work.

I've tried viewing PRs with .js, .html, .pl, .pm and .t extensions, no luck.

I've tried clearing my cache, logging out of bitbucket, restarting my browser, but no luck.

Word occurence, toggle diff text and the diff loading features are all operating, but not syntax highlighting (and possibly the " Improve the default font-family and size of lines of code in Source view." setting).

Example JS file
![image](https://user-images.githubusercontent.com/1937814/36068373-2b9607ca-0f28-11e8-810f-74ad31fbc87d.png)
Settings
![image](https://user-images.githubusercontent.com/1937814/36068376-39ff3584-0f28-11e8-8625-5fb84b30c2b0.png)

**Comment by reyronald** [comment]
Hello @dpekkle 

Can you tell me what browser you are running on? Which version of the extension do you have? Can you check if there's any errors in the developers console?

Open this PR and let me know if you don't see any syntax highlighting on it either https://bitbucket.org/atlassian/atlaskit/pull-requests/4412/fix-component-move-scroll-lock-style/diff?w=1

This is how I see it by the way, just so you have a reference:

![image](https://user-images.githubusercontent.com/7514993/36069842-fa2bdf4a-0ec6-11e8-850e-e4dce4257f57.png)

**Comment by dpekkle** [comment]
Hi @reyronald 

I'm running Google Chrome Version 64.0.3282.140 (Official Build) (64-bit), Windows 10.

Refined Bitbucket is Version: 3.5.0, from the chrome webstore.

Console, no highlighting:
![image](https://user-images.githubusercontent.com/1937814/36070067-909ac8bc-0f47-11e8-8043-c5011b8b452c.png)

**Comment by dpekkle** [comment]
Thought it might be one of my extensions (ublock) involved so I've disabled all other extensions.

![image](https://user-images.githubusercontent.com/1937814/36070085-006180b4-0f48-11e8-9eed-05983d2aa87a.png)

**Comment by reyronald** [comment]
I was checking the code and I think I already know what it is... when did you first install the extension?

**Comment by dpekkle** [comment]
About 5 hours ago today

**Comment by dpekkle** [comment]
About 5 hours ago today.

**Comment by reyronald** [comment]
Perfect. 

I changed some of the configuration settings in the latest version and I just noticed that I forgot to update the setting related to syntax highlighting. It will work on anyone that had the extension prior to that version, but not on someone who installed it recently, like you!

My deepest apologies, that was a totally my fault :(, thank you for taking the time to come and letting me know! I'll release a patch tomorrow and hopefully everything will be fixed.

And by the way, I'm not familiar with the .pl, .pm and .t extensions you mentioned, can you tell me if they are any of the ones listed here, and which one? http://prismjs.com/test.html

**Comment by dpekkle** [comment]
No worries, thanks for the really quick turnaround.

.pl is perl, which is already on that list 

.pm and .t are also both perl (modules and test files respectively). No syntactic differences, so whatever perl interpreter you have should cover it.

Another related one is .tt which is for template toolkit, perl based templating for web pages (http://template-toolkit.org/docs/index.html). Usually doesn't look too different to HTML, but might be a bit trickier.

**Comment by reyronald** [comment]
Cool, the extension already has the Perl grammar, but only associated to .pl files, so we are going to have to add the rest manually.

If you'd like to contribute you can just add the entries to the list here : https://github.com/refined-bitbucket/refined-bitbucket/blob/dev/src/syntax-highlight/language-ext.js and submit a pull request! If you don't have the time I'll do it myself before releasing the patch tomorrow :)

**Comment by reyronald** [comment]
I just published v3.6.0, please let me know if it is working for you now! Make sure to verify the checkbox for the feature is enabled in the Options page and that your cache is refreshed when you go to Bitbucket!

**Comment by dpekkle** [comment]
Looks good, working now thank you :)
