### ISSUE TITLE
[FR] Hide pluses / minuses

### ISSUE THREAD

**Issue by dmrickey** [refined-bitbucket/refined-bitbucket#149]
An option I think would be super helpful is the ability to hide the pluses/minuses in a changeset.  The colors are enough for me (though this option would have to be off by default for colorblind users).  I often find myself copying code between pull requests to make sure it does what it should.  So whether it's me copying/pasting it between IDEs or diff tools, the pluses/minuses always get in the way.  

Let me know the feasibility of this.  While this idea makes perfect sense to me, if I somehow didn't explain my thoughts well enough let me know and I'll try again.

**Comment by reyronald** [comment]
Hello @dmrickey , thank you for coming in and suggesting a feature!

I can complete relate to that feeling, I copy code from the diffs all the time and always have to remove all of the pluses and minuses manually! It's a pain! It makes complete sense and don't know how I didn't think of it myself 😅 , so I think it's a great idea!

I got excited by it and went ahead and coded a prototype, but went one step further just to make the experience more consistent with how it is now and to avoid causing any discomfort for colorblind users, or just users that like to see their pluses and minuses, take a look:

![remove-plus-and-minus-from-diff-2](https://user-images.githubusercontent.com/7514993/36133714-68da1f98-1056-11e8-9c3a-2c7e790ce69d.gif)

I managed to do it in a way that would visually preserve the characters in the diff, but wouldn't be carried over to the clipboard when copying the contents of the diff. What do you think? Is this the usability you had in mind?

**Comment by apitzele** [comment]
@reyronald - very nice.  I would find this feature useful as well.
