### ISSUE TITLE
Last updated user name in pull request list

### ISSUE THREAD

**Issue by bpahan** [refined-bitbucket/refined-bitbucket#154]
Could you add "by {username}" to the end of the second row on pull request item

![image](https://user-images.githubusercontent.com/2129348/36310400-8f9b431e-1330-11e8-9364-95db473b7cb9.png)

**Comment by reyronald** [comment]
You mean the username of whoever updated the PR last? Not the creator of the PR ?

**Comment by bpahan** [comment]
Yes. 

It can be some workaround on this issue https://bitbucket.org/site/master/issues/13021/add-reviewer-status-of-needs-work-to
No matter how many people vote for this issue, Bitbucket team won't done it

**Comment by reyronald** [comment]
I see! Yeah Atlassian is very slow when attending customer requests for issues.

I'll take a look, I think it could be done. Thanks for the suggestion!

**Comment by drexler** [comment]
@reyronald  i can take a stab at this. I need further clarification though.

 Looking the [BitBucket API](https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Busername%7D/%7Brepo_slug%7D/pullrequests/%7Bpull_request_id%7D),  @bpahan  are you looking for:
- the username of the person with the last activity (comments, commits etc) on the PR? or 
- specifically the username of person with the last commit on the PR?

**Comment by bpahan** [comment]
The first. Any activity

**Comment by reyronald** [comment]
I wouldn't include it if it requires more than one API call per pull request. Imagine, that page shows dozens of PR rows, if that was the case we would end up with 25+ HTTP requests every time we visited that list, which I don't think would be a responsible thing to do :/

**Comment by bpahan** [comment]
But if you make an option in settigns anyone will make his own decision

**Comment by drexler** [comment]
@reyronald although your concerns are valid, i tested this with a large PR listing by viewing the list of merged/declined pull requests within my team with this feature enabled. The user experience was still the same.  Performance-wise, i'll say it's still the same.  I have the implementation done in #187.  I'm open to suggestions on improving the PR like the last time :wink:
