### ISSUE TITLE
Close branch checkbox being defaulted to on in PR edit view even when the PR settings specify it as off

### ISSUE THREAD

**Issue by stevemuskiewicz** [refined-bitbucket/refined-bitbucket#155]
When running Refined Bitbucket in Chrome (Mac), if you create a PR via either the Bitbucket UI or the API and uncheck the "Close source branch" option, then go to the "Edit" view for the PR, the option is shown as checked by default with no user action to actually change it.

Disabling Refined Bitbucket and viewing the same Edit page (or using a different browser) shows the expected result - the "close branch" option is not checked by default in the PRs where is was not originally set to on.

**Comment by reyronald** [comment]
I can't reproduce this :/. It is true that if the feature is enabled in the extension, it will check the "close branch" checkbox every time you try to Edit the PR, that is indeed something I should fix, but if I disable the feature through the Options page, the checkbox is not manipulated at all when I try to create or edit PRs. Are you completely certain this is the behavior that you are seeing on your end?

**Comment by stevemuskiewicz** [comment]
My bad, I didn't think to check the options and that option was enabled.  When I disabled it now I don't see the close branch option getting checked any more.

However its behavior does seem a little confusing, it reads 'Check the "Close anchor branch" checkbox by default when creating a new pull request' but in this case I was *editing* an existing pull request, so I guess I wouldn't have expected it to be toggling this option in that particular case.  Can you either clarify the wording of the option or make it behave such that it only applies when creating a new pull request and not when the "Edit" screen is used?

**Comment by reyronald** [comment]
> Can you either clarify the wording of the option or make it behave such that it only applies when creating a new pull request and not when the "Edit" screen is used?

Yes, definitely. I agree with you on that, it shouldn't actually enable the checkbox when editing the PR! I'm fixing it.

Thank you for pointing that out, I guess I didn't give it much thought when I did initially 😅
