### ISSUE TITLE
SCSS syntax highlighter seems to remove characters in the code diff

### ISSUE THREAD

**Issue by alisspers** [refined-bitbucket/refined-bitbucket#160]
It seems as though the syntax highlighter removes characters in the diff. I've only found this in SCSS files though (did a quick scan through a few HTML/JS files and they had no problem).

This first image is the diff without syntax highlighting:

![screen shot 2018-02-27 at 13 12 42](https://user-images.githubusercontent.com/208699/36728314-9ca5ba6a-1bc0-11e8-8bbf-21f2aded0727.png)

And here's with the highlighting, notice how it says "hite-space":

![screen shot 2018-02-27 at 13 09 13](https://user-images.githubusercontent.com/208699/36728342-b8946528-1bc0-11e8-93bd-ed17c5589462.png)

I was updated to 3.7.0 this morning, I'm not sure whether or not this was there before the update.

**Comment by reyronald** [comment]
Thank you for letting me know! I'll take a look into it.

If you could provide the HTML for the diff's node it would be extremely helpful! It's a section with the class `uudiff`

**Comment by alisspers** [comment]
Sure thing, here's the `hite-space`-node, with and with highlighter enabled:

WITHOUT HIGHLIGHTER:

	<div class="udiff-line common">
		<div class="gutter" id="...">
			<a class="add-diff-comment add-line-comment" href="#add-comment" title="Add a comment to this line">
				<span class="aui-icon aui-icon-small aui-iconfont-add-comment">Add a comment to this line</span>
			</a>
			<a class="line-numbers" data-fnum="34" data-tnum="34" href="..."/>
		</div>
		<pre class="source">white-space: nowrap;</pre>
	</div>


WITH HIGHLIGHTER:

	<div class="udiff-line common">
		<div class="gutter" id="...">
			<a class="add-diff-comment add-line-comment" href="#add-comment" title="Add a comment to this line">
				<span class="aui-icon aui-icon-small aui-iconfont-add-comment">Add a comment to this line</span>
			</a>
			<a class="line-numbers" data-fnum="34" data-tnum="34" href="..."/>
		</div>
		<pre class="source language-scss">
			<span class="token property">hite-space</span>
			<span class="token punctuation">:</span>nowrap
			<span class="token punctuation">;</span>
		</pre>
	</div>

Is that good enough?

**Comment by reyronald** [comment]
Perfect! I already figured it out, fix is coming tomorrow! Thank you!

**Comment by reyronald** [comment]
Hey @alisspers , just released a new version, please verify if the error is fixed when you update and let me know!

**Comment by alisspers** [comment]
Just looked at the same PR as before and it works great now. Thanks for the fast response!
