### ISSUE TITLE
sometimes extra minus signs in diff view

### ISSUE THREAD

**Issue by requaos** [refined-bitbucket/refined-bitbucket#168]
I do not have exact reproduction steps, but sometimes in the diff view there will be an extra minus(-) on removed lines... its not a big deal but makes my eyes twitch from the single char offset, makes my brain think "wait, didn't just run that through the linter before pushing?"

**Comment by reyronald** [comment]
Could you post a picture of one instance of this case, both with the feature on and off, so I can see the expected behavior versus the wrong one? That can maybe give me an idea of where to start to look for the possible bug.

Thanks for letting me know!

**Comment by JimPatterson** [comment]
I think this is related to the fixes for #161.  The option "Don't carry pluses and minuses to clipboard when copying diff's contents" off, fixes the display.  Here is a screen shot of the "broken" state: 
![extra-diff-markers-bad](https://user-images.githubusercontent.com/1703168/36980788-5a606356-2059-11e8-88dd-ed142f4abab3.png)

Notice how the top two lines look correct, but the bottom block does not.  Here is the same screenshot with the option off: 
![extra-diff-markers-good](https://user-images.githubusercontent.com/1703168/36980832-791ff036-2059-11e8-9b7d-b8d61efd62ff.png)

I'm not sure what condition in the diff causes the problem, sometime one line diffs work and sometimes they don't, same for multi line diffs.

Here are the html blocks for line 49 from the two screen shots.



[extra-diff-markers-bad.txt](https://github.com/refined-bitbucket/refined-bitbucket/files/1781228/extra-diff-markers-bad.txt)
[extra-diff-markers-good.txt](https://github.com/refined-bitbucket/refined-bitbucket/files/1781229/extra-diff-markers-good.txt)

**Comment by davidmankin** [comment]
I just filed #175 with the same issue.

**Comment by reyronald** [comment]
Just letting everyone know that I'm already working on a fix for this. 

If anyone has the time and is willing to load a development version of the extension in their browsers to test the fix in their environments before it is pushed into a release, let me know, it would help to make sure the fix is actually covering all of the cases.
