### ISSUE TITLE
can't seem to get the option to show the "source branch name" in the pull request list view to work

### ISSUE THREAD

**Issue by btenny** [refined-bitbucket/refined-bitbucket#169]
This is the option I want to use:
 ![image](https://user-images.githubusercontent.com/1723948/36854478-1bdee728-1d3f-11e8-8129-94fef68b42f6.png)

But my pull request list view shows unchanged.

**Comment by reyronald** [comment]
It should only work in the view from a URL like `https://bitbucket.org/user/repo/pull-requests/`, do you have any errors in the console?

Also, can you see the counters in the sidebar for the number of branches and open pull requests?

**Comment by btenny** [comment]
Yes, I can see the counters in the sidebar for the number of branches and open pull requests, that option is working fine.

Here is the console:

![image](https://user-images.githubusercontent.com/1723948/36854914-3cdc9a00-1d40-11e8-8b8e-6eb0c1e57046.png)

**Comment by btenny** [comment]
and my URL is: https://bitbucket.org/datatrac/cops_statis/pull-requests/

**Comment by reyronald** [comment]
Just to be sure, did you enable the feature in the Options page through `chrome://extensions` ?

**Comment by btenny** [comment]
Yup...

![image](https://user-images.githubusercontent.com/1723948/36855421-6684d0c4-1d41-11e8-8c99-5178782148d5.png)

**Comment by reyronald** [comment]
Ok, in the console's network tab, filter for requests to `api.bitbucket.org` like so, and let me see which ones you have in there:

![image](https://user-images.githubusercontent.com/7514993/36855557-2caaea42-1d4a-11e8-9a85-e568d24fe551.png)

**Comment by btenny** [comment]
here you go...

![image](https://user-images.githubusercontent.com/1723948/36856063-1a41017c-1d43-11e8-8eb9-f7ed8e43b53b.png)

**Comment by reyronald** [comment]
Enable the "Set "Ignore whitespace" ON by default when entering a Pull request from the Pull requests list page" option and try again, let me know **if that feature works**! It should append `?w=1` to each pull request link.

**Comment by reyronald** [comment]
Also, let me see the markup for any DOM node that is a row of the table `table.pull-requests-table`, it should have the class `.pull-request-row`. Strip any confidential information from it if you need, I only need to see the structure of the HTML

**Comment by btenny** [comment]
Enabling that option made it work!  Thanks.  The pull request list view now shows the extra info.  What is that "whitespace" option?  It is not clear what it does.

**Comment by reyronald** [comment]
It opens the pull request with whitespaces ignored by default. Typically what Bitbucket would have you do is open the pull request, click the "..." dropdown of any diff and check the "Ignore whitespace" option, which will then refresh the page and load all the diffs again. 

![image](https://user-images.githubusercontent.com/7514993/36861162-80b0b284-1d59-11e8-8c53-2374c065c0e6.png)

This is cumbersome because the user has to check that option manually EVERY time he opens a PR, and then wait for the PR to reload. That's what the feature intends to avoid.

---

P.S.: I'm going to leave this issue open, because those are two completely different features that shouldn't depend on each other, so you definitely found a bug, thanks for discovering it! I never noticed myself because I always have all of the features enabled 😅

**Comment by btenny** [comment]
OK thanks... and yes, I would love this bug fixed because I **don't** want to use the "ignore whitespace" option.

**Comment by reyronald** [comment]
Will fix it for the next release! :)

**Comment by btenny** [comment]
Oh good... when will it be?  I am loving these extensions, but my favorite one is the one that is broken :-)

**Comment by reyronald** [comment]
@btenny I'll try to put it out by Monday  Not soner just because I've been busy with other projects.

Glad to hear you are loving the extension! :D

**Comment by reyronald** [comment]
@btenny If you disable the "whitespace" feature again, is the "source branch name" lost too ?

**Comment by btenny** [comment]
Yes

**Comment by reyronald** [comment]
@btenny I tried reproducing the bug on my machine two days ago by setting my Options like you have them in the screenshot you uploaded, but I couldn't! Disabling the "white-space" feature does not remove the "source branch name" feature for me ! 😕 

Can you confirm if it's a caching issue ? (clear your cache after changing the options maybe?)

If that's not it I honestly don't know what's causing the bug. It would be great if you could debug through it with a development version of the extension. Let me know if you have time so I can guide you through it.

**Comment by btenny** [comment]
I cleared cache and still not working.

These options:
![image](https://user-images.githubusercontent.com/1723948/37152784-8141142e-22a8-11e8-9365-8affb5fe2435.png)

Get me this:
![image](https://user-images.githubusercontent.com/1723948/37152796-8ad2d25c-22a8-11e8-80c6-5b8df8bbceef.png)

If I then, enable the "whitespace" option, then I see this:
![image](https://user-images.githubusercontent.com/1723948/37152868-c2da1494-22a8-11e8-96e6-7414a203afd3.png)

**Comment by btenny** [comment]
I really need to see the source branch but I do not want the whitespace option.  I thought you said on March 1st you noticed/found the bug with the whitespace option?

**Comment by btenny** [comment]
Thanks for the fix!  I hope this fix will also make the "created on" date show too.

**Comment by reyronald** [comment]
@btenny No problem! The release is already out, update, test it, and let me know !

**Comment by btenny** [comment]
Excellent!  It is fixed, this is a good day.  Thanks for being so responsive.

**Comment by reyronald** [comment]
You're welcome! Thanks for reporting the issue. It's always great when users are willing to be involved in improving the product!
