### ISSUE TITLE
please add support for Jenkinsfile*, or other files with no extension using crunch bang syntax

### ISSUE THREAD

**Issue by requaos** [refined-bitbucket/refined-bitbucket#170]
When I write Jenkinsfiles by hand I use groovy, which I indicate in the Jenkinsfile on the firstline:
```
#!groovy
```
I also write script files in linux without dot extensions:
```
#!/bin/ruby
```
```
#!/bin/perl
```
```
#!/opt/python2.7/bin/python
```
et al... 
This is a long standing convention in *nix world, any ideas on implementing support for parsing the crunch bang line for syntax highlighting language choice? It could be any file without an extension, and not just Jenkinsfiles

**Comment by reyronald** [comment]
The issue that I see with it is that the extension syntax highlights diffs, not entire file contents. If the shebang is not part of the diff, it won't be able to find it anywhere so nothing would be highlighted in that case. What do you think?

**Comment by requaos** [comment]
hrmm, good point... what about a language selector option for diff views with an unrecognized language?

**Comment by reyronald** [comment]
You mean like a button or dropdown right in the diff header or something similar?

**Comment by requaos** [comment]
yeah, something like that... not trying to burden the ui/ux judgment call by prescribing a solution

**Comment by reyronald** [comment]
In your use case, is it possible to determine which language grammar to apply based on the filename and/or file path? I'm thinking that allowing the user to configure a mapping of rules to grammars could also be a way to go, so that the user can tell the extension "all the files that match the following rule or pattern should use this grammar", but don't know if that could actually be more useful than the dropdown option.

**Comment by requaos** [comment]
that kinda goes back to parsing the shebang...

**Comment by reyronald** [comment]
I don't think it would be the same, because the shebang is part of the contents of the file, not the filename. Also, with shebang parsing you wouldn't necessarily need to configure anything extra as a user.

**Comment by drexler** [comment]
Created pull request #174 to handle specific files that are universally known to have a particular language. Example Jenkinsfile is groovy-based and Vagrantfile is ruby-based.

**Comment by drexler** [comment]
@reyronald this issue can be closed.

**Comment by reyronald** [comment]
Yeah, I think that given our conversation the best way to approach this kind of files is to handle them specifically by filename like it was done with #174.

Thank you @drexler for working on that! 🙏 

Closing.
