### ISSUE TITLE
[FR] Add option to toggle comments in diffs

### ISSUE THREAD

**Issue by reyronald** [refined-bitbucket/refined-bitbucket#172]
Just like GitHub works! 😄

**Comment by deepakrb** [comment]
I'd really like to see this feature, your ability to review a PR degrades as more and more people begin to comment and it breaks up changes into changes and other peoples opinions. It'd be nice to switch them all off so you can have the same experience the first reviewer had.

It'd also be nice to be able to toggle them on or off per file

**Comment by kopach** [comment]
Just noticed this new feature. Super useful. Thank you!

**Comment by reyronald** [comment]
Thank you @kopach ! I released it yesterday! Glad you are finding it useful 😄
