### ISSUE TITLE
Collapse isn't working

### ISSUE THREAD

**Issue by dmfay** [refined-bitbucket/refined-bitbucket#178]
hi! This may be the same issue as #131. I'm using Vivaldi and Chrome on OSX, and have the following collapse patterns (the second should be redundant, but just in case):

```
**/package-lock.json
package-lock.json
```

It's still trying to load package-locks and I'm seeing the 'Oops! You've got a lot of code in this diff and it couldn't load with the page' message for them and for subsequent files.

**Comment by reyronald** [comment]
I'm not sure if I understood correctly. The auto-collapse feature does not prevent Bitbucket from trying to load the files, it just collapses (or hides) the diff from view. If you want them to be removed entirely, use the "Diff ignore" feature instead.

Let me know when you try that.

**Comment by dmfay** [comment]
That worked, thanks! Great work with this btw :)

**Comment by reyronald** [comment]
Thank you! Glad you are enjoying it! ^^
