### ISSUE TITLE
Feature request add a custom style to bitbucket pages

### ISSUE THREAD

**Issue by ghost** [refined-bitbucket/refined-bitbucket#181]
Being able to add a style element on the page would be nice, right now I am using a bookmarklet, which kinda sucks. This could be very helpful to change the tab length on the overview page. 

`.refract-container .source { tab-size: 4 !important; }`

The bookmarklet I am currently using:

`javascript:(function(){ var style = document.createElement(%27style%27), styleContent = document.createTextNode(%27.refract-container .source { tab-size: 4 !important; }%27); style.appendChild(styleContent ); var caput = document.getElementsByTagName(%27head%27); caput[0].appendChild(style); })();`

**Comment by johnzhanghua** [comment]
@reyronald  How to set up the css? I pasted a CSS from https://userstyles.org/styles/156271/bitbucket-dark-fixes-by-prognoz-deprecated. But once I change some options above or close the option. 

It disappears.

**Comment by reyronald** [comment]
Hello @johnzhanghua , there's a limit to how big the size of the stored styles can be. It cannot exceed 8,192 bytes as measured by its JSON stringification. The styles you linked are just too big for the extension to handle.

You can install that specific theme using either Stylist or as a userscript instead, I believe the site that you linked guides you through both choices.

I'll make this more clear in the next release of the extension, thank you for pointing it out!

**Comment by johnzhanghua** [comment]
@reyronald  Thank you for the reply. I've installed the dark theme via userScript. But looks there is some colour conflict of the deleted code. 

I've customized the css as well.
