### ISSUE TITLE
Rakefile support

### ISSUE THREAD

**Issue by hk0i** [refined-bitbucket/refined-bitbucket#184]
Rakefiles in diffs aren't being properly highlighted it seems

![image](https://user-images.githubusercontent.com/755669/37442350-0fe65fd0-27c3-11e8-82e9-4a78a5f19d6c.png)

**Expected:** `Rakefile`s to be highlighted as ruby code
**Actual:** No highlighting for `Rakefile` at all.

This is probably a quick fix I can try digging into later when I have some time if someone can throw me a hint on where it might be.

**Comment by reyronald** [comment]
Hello @hk0i ,  thanks to the work from @drexler in #174 this is already pretty easy to fix. Only thing you have to do is add an entry to `rakefile` here, between `jenkinsfile` and `vagrantfile`:

https://github.com/refined-bitbucket/refined-bitbucket/blob/ffd868f762ca3b871a2170176b82012ca7ea3b28/src/syntax-highlight/language-ext.js#L69-L73

So it would look like this (it has to be lowercase)

```diff
    // Universally named files
    jenkinsfile: 'language-groovy',
+    rakefile: 'language-ruby',
    vagrantfile: 'language-ruby'
};
```

Looking forward to your pull request! Please remember to add an entry in the CHANGELOG below the **Language support** header.

**Comment by hk0i** [comment]
Very neat, will be sending pr shortly.
