### ISSUE TITLE
Could we get something more closely resembling the badges that BB previously had for PR counts?

### ISSUE THREAD

**Issue by brianespinosa** [refined-bitbucket/refined-bitbucket#185]
If I recall correctly before they robbed us of them, the PR badges looked something like this:

![image](https://user-images.githubusercontent.com/1161781/37487400-ac536d8c-284e-11e8-998f-d2fc494e64d6.png)

We would basically get that with this:
```
.__rbb-badge {
    position: absolute;
    right: 4px;
    background: #a00;
    border-radius: 16px;
    color: #fff;
    line-height: 1;
    padding: .125em .375em .25em;
}
```

I am happy to open a PR for this if it is something there is consensus on. I am not opposed to something else for the color of the badge, etc.

**Comment by reyronald** [comment]
Could you post a picture of how they look like when collapsed? And also how they would look like when the number has three or four digits?

**Comment by brianespinosa** [comment]
![image](https://user-images.githubusercontent.com/1161781/37488684-acbf1844-2852-11e8-902d-14e02de579f0.png)
This is how they look currently (if that is what you mean by "collapsed"). Do you mean when there are none?

I made sure those styles still work when there are multiple digits:
![image](https://user-images.githubusercontent.com/1161781/37488798-f8c28848-2852-11e8-872d-12a5a235d482.png)

**Comment by brianespinosa** [comment]
Ah. THIS is what you mean by collapsed:
![image](https://user-images.githubusercontent.com/1161781/37488873-1ee6ad10-2853-11e8-95ad-768637bcfcb3.png)

I can look at raising them to the top right when collapsed. I'll have to see if there's a parent selector for that to make it easy.

**Comment by reyronald** [comment]
Yup, that's what I mean. I didn't add a background to the badge to not take unnecessary space when the menu was collapsed so that the numbers wouldn't stamp on top of the icons. Would like to know what the rest of the user-base would feel like, but sadly they don't frequent this repo frequently =P

**Comment by reyronald** [comment]
For reference, this is how it looks right now:

<table>
<tr>
<td>
<img src="https://user-images.githubusercontent.com/7514993/35759127-0f886b44-084e-11e8-9e3a-58e9ce3da71a.png" alt="expanded"/> <br />
Expanded
</td>
<td><img src="https://user-images.githubusercontent.com/7514993/35742830-1c604af8-0812-11e8-936b-f6083599fb45.png" alt="collapsed" /> <br />
Collapsed</td>
</tr>
</table>

**Comment by brianespinosa** [comment]
Seems like there is no deterministic class to target for collapsed that I am seeing. They inline the width. The best way would probably be to add this:

```
div[style*="width: 64px"] .__rbb-badge {
    right: -4px;
    top: -4px;
}
```
Which gives this:
![image](https://user-images.githubusercontent.com/1161781/37489297-61bde47c-2854-11e8-83c8-230bbabe9298.png)

These numbers could use some fine tuning. Probably padding could be reduced. I could put a more solid proposal with better padding if you think there would be interest. Might be best to just submit it as a PR and discuss over code?

**Comment by reyronald** [comment]
Don't know if you noticed but the markup of the sidebar actually changes when it is collapsed or expanded and I in fact insert different HTML for each mode, so that would have to be taken into account as well.

I honestly don't know if there would be community interest :(, not sure if you are still willing to invest time in it taking that into account! It'll probably wouldn't be merged for a while until some people come to see it and comment

**Comment by brianespinosa** [comment]
I'll put something together. I'm more than happy to invest some time on this, even if nothing happens with it. That's how this whole open source thing works. ;)

**Comment by reyronald** [comment]
Fair enough! Glad to have you on board :)

**Comment by jwallet** [comment]
red badges is diffinetively more common to see that one without it, slack, rocket chat and other chat app, windows has some app doing that too like Windows Mail, I really like the suggestion here.

btw, this feature only works while watching a pr, we see `?` in Pull Request list for the current repo,

you can also play with the alpha color, or opacity of the element to not cover the one below, but it will look pink
