### ISSUE TITLE
Firefox add-on 3.7.3 does not work

### ISSUE THREAD

**Issue by drexler** [refined-bitbucket/refined-bitbucket#188]
Installed and attempted to use it on the following Firefox versions:

- Firefox version 59.0.1 (64 bit)
- Firefox Developer Edition version 60.0b4 (64bit)

Furthermore, i built the add-on from source and the results were the same - installs correctly on both browsers - Chrome & Firefox but the latter never works. 

Most likely, i think the issue is with how the addon is being generated.

**Comment by reyronald** [comment]
Firefox Add-on is working fine as of version v3.8.0 with no change, (evidenced by #198), so I'm closing this.
