### ISSUE TITLE
[FR] Add the ability to create a PR from the compare page

### ISSUE THREAD

**Issue by deepakrb** [refined-bitbucket/refined-bitbucket#189]
Bitbucket has the convenient but hidden feature 'Compare' which can be found at https://bitbucket.org/{USER}/{REPO}/branches/compare . Or by clicking the '+' in a repo and clicking the 'Compare branches or tags' button.

Its a pleasant diff page but I would like a CTA which allows me to take the two branches I am comparing an 'Create a PR' where the feature and target branches are set from the branches I was looking at.

**Comment by drexler** [comment]
@reyronald i'll take a stab at this.

**Comment by deepakrb** [comment]
cheers @drexler , I made a start on it here https://github.com/deepakrb/refined-bitbucket/commits/merge-compare (It looks similar to the 'Create Pull Request' link on the branches page - I need to fix whitespace diffs) but If you want to do your own implementation I am happy to leave it

**Comment by drexler** [comment]
@deepakrb sweet! Go ahead with your implementation;  you're a bit ahead of me here.
