### ISSUE TITLE
Set page-specific constraints for scripts (matches)

### ISSUE THREAD

**Issue by andremw** [refined-bitbucket/refined-bitbucket#20]
Some scripts will only be run at specific pages, so in order to avoid loading all content for all pages, we load only the content that will be useful.

**Comment by rproenca** [comment]
And this would fix another issue that we have today: code like the one below runs forever on pages in which 'container-id' does not exist.

``` javascript
    function doSomethingWhenReady() {
        const intervalId = setInterval(() => {
            const container = document.getElementById('container-id');
            if (!container) return;

            clearInterval(intervalId);

            ...
        }, INTERVAL);
    }
```
