### ISSUE TITLE
Feature Request: Custom Tab Indentation Size of Code

### ISSUE THREAD

**Issue by peterkrieg** [refined-bitbucket/refined-bitbucket#202]
First of all, I want to second the positive things others have said about this extension - I'm glad I found it, it makes bitbucket a lot better!  Thanks for the great work!

When viewing code using tabs, bitbucket defaults the tab size to 8 spaces, which I feel makes the code a bit unreadable, especially when a user is accustomed to 2 space tabs, for example, instead.   A user can change the code tab size of any page by appending `&ts=2`  as a url param to any page, but who wants to do that and then refresh the page every time?

I think it would be nice to have an option that the user can select their desired tab size (2/4, or whatever) and then the extension injects CSS as necessary to achieve this.

I already know the CSS rules required and would be happy to make a PR, just wanted to gauge interest in this first.

**Comment by reyronald** [comment]
Hello @peterkrieg ! Thank you for your kind words! It 's really nice to know that the work myself and other contributors have been doing for the extension is appreciated! ^^

Regarding the feature, this is a totally valid and would be very useful! If you have the time to make a PR it would be great. It should be very simple to implement, let me know if you need any guidance or help, and looking forward to it!

**Comment by peterkrieg** [comment]
Alright, sounds good @reyronald.   I will make a PR and let you know if I have any questions, thanks!

**Comment by peterkrieg** [comment]
I didn't get around to this for a while because of the day job.. 🙂  but I added PR https://github.com/refined-bitbucket/refined-bitbucket/pull/209.   Let me know if it looks okay or if you want me to change anything!
