### ISSUE TITLE
Pull request and branch count for Firefox

### ISSUE THREAD

**Issue by jperasmus** [refined-bitbucket/refined-bitbucket#206]
Hi there,

I am so happy that I stumbled upon this extension today. A lot of the things you've added is actual things I've posted to BitBucket before as feature requests. 👏🏼

Noticed a small bug on Firefox now: the PR and branch counts don't seem to show. On Chrome they show up nicely.

**Chrome:**
<img width="239" alt="counts-chrome" src="https://user-images.githubusercontent.com/6787452/39565303-be0e200a-4eb7-11e8-82e1-5821fdfc05b2.png">

**Firefox**
<img width="240" alt="counts-ff" src="https://user-images.githubusercontent.com/6787452/39565317-ca7ca406-4eb7-11e8-8fd0-9264ea3b9c92.png">

**Comment by reyronald** [comment]
Hello @jperasmus ! Thank you for your kind words! I'm glad the extension has been helpful to you! I would appreciate it if you could rate it in the Chrome Webstore and Firefox's Add-ons site, it helps give the extension more visibility so other users can find it!

Regarding the issue you mention, this already was solved in #197 by @drexler but it's not yet released. It will be coming in the next version 3.9.0, hopefully next week :)!

Something else in that regard, I myself don't use the Firefox version at all, so it's entirely possible that there might be other creeping bugs, issues, or inconsistencies over there. If you find any other, please let me know!

**Comment by jperasmus** [comment]
Sure, I'll be sure to go and rate the extension in the add-on sites. Playing with it for another week or so and planning to suggest it to the rest of our team as well.

Apologies for the duplicate, I tried searching for a similar issue but didn't find it before.

I'll add new issues if I find any while using FF. Would like to possibly contribute a fix as well at one point.

**Comment by reyronald** [comment]
> Apologies for the duplicate, I tried searching for a similar issue but didn't find it before.

Not at all! I really appreciate every bug report or issue created. The original issue didn't directly mention the features it was affecting, so it's not your fault :).

Looking forward to have you on board!
