### ISSUE TITLE
Add ability to copy file path

### ISSUE THREAD

**Issue by kopach** [refined-bitbucket/refined-bitbucket#210]
I very often do copy path of file I'm reviewing to clipboard in order to search for it in my editor and check it there. So, I'm wondering, would it be possible to add file path copy button next to the file name in bitbucket? Or, maybe just make existing file icon clicable and by clicking on it - copy file path to clipboard.

**Comment by reyronald** [comment]
Hi @kopach , long time no see.

You mean in the header of the diff when viewing Pull Requests or Commits?

**Comment by kopach** [comment]
Hi @reyronald, yes, exactly 😊

**Comment by reyronald** [comment]
I'll see what I can do! Although I've been pretty busy lately, so be patient =P

**Comment by kopach** [comment]
I think, the good example of `Copy to clipboard` functionality would be Bitbucket's git command copy. Not sure, but maybe, there is a way to somehow reuse that functionality (or at least icon/styles). 
![copy to clipboard](https://user-images.githubusercontent.com/8749624/40370259-2359e700-5de0-11e8-8ba2-d76c4d8ad6c3.png)

**Comment by reyronald** [comment]
Functionality-wise I don't think this feature is very challenging at all, should only be a few lines of code. 

The icons and styles though, thank you for pointing that out, could definitely be reused from there!

**Comment by reyronald** [comment]
@kopach check out #215

**Comment by kopach** [comment]
excellent, thank you @reyronald
