### ISSUE TITLE
Support for clojure syntax

### ISSUE THREAD

**Issue by dguayrobotiq** [refined-bitbucket/refined-bitbucket#211]

**Comment by reyronald** [comment]
Hello @dguayrobotiq , thanks for the suggestion.

Feel free to modify the https://github.com/refined-bitbucket/refined-bitbucket/blob/dev/src/syntax-highlight/language-ext.js file and submit a PR!

**Comment by dguayrobotiq** [comment]
@reyronald I see clojure is in that list: http://prismjs.com/download.html#themes=prism-okaidia and tried adding this line to the `language-ext.js` but it's not working at all.

`'.clj': 'language-clojure'`

**Comment by dguayrobotiq** [comment]
@reyronald Adding `'.clj': 'language-clojure',` to `language-ext.js` doesn't seem to work. I got the class name from here: https://github.com/troglotit/prism-clojure

**Comment by reyronald** [comment]
Did you compile the extension, loaded it into your browser, enabled it and disabled the production one?

**Comment by dguayrobotiq** [comment]
Yes to all of this ! I had to remove the `applications` key in `manifest.json` though to make it work.

**Comment by reyronald** [comment]
Checkout the branch `lang-clojure` and try it there, let me know how it goes.

**Comment by dguayrobotiq** [comment]
@reyronald Weird, that's working ! Not sure what I did wrong... Can you make a PR?

**Comment by reyronald** [comment]
Already did! #212 

Nothing wrong with what you did. The Prism version I was using so far didn't include Clojure support, I had to upgrade it, check the PR if you're curious.

Will be included in the next release!
