### ISSUE TITLE
Extra leading whitespace in diff sometimes

### ISSUE THREAD

**Issue by wuservices** [refined-bitbucket/refined-bitbucket#218]
In some diffs like this one, I've noticed there's a leading whitespace before the changed lines in the diff. Now that somebody has falsely finally called this out on my PR, I've looked a little more into it.
<img width="1540" alt="screen shot 2018-05-26 at 9 32 53 am" src="https://user-images.githubusercontent.com/190434/40578376-fa44fb30-60c7-11e8-852f-10990e5cd2ef.png">

In this screenshot you can see there's 1 space added after the `<pre>` starts for the code on the last added line. I don't have any patterns yet, so fingers crossed you might have a lead, otherwise I'll continue to gather data here.

If I disable the extension and refresh, the problem goes away. I have of course also checked the file to make sure the whitespace isn't there, and this isn't the first time I've seen this issue.

**Comment by reyronald** [comment]
Hey @wuservices ! Thanks for reporting! Sorry about that, to be honest I've noticed that bug myself too but just ignored it 🙈 

Don't worry about gathering more data, I think this is directly related with the "Don't carry pluses and minuses to clipboard when copying diff's contents" feature and I have some clues as to why it may be happening. If you disable that one feature alone in the Extension options page it should go back to normal without having to disable the entire extension (not 100% sure though), so if it's getting in the way of your code review experience you can do that while I push a fix for it :)

**Comment by wuservices** [comment]
I can confirm that disabling "Don't carry pluses and minuses to clipboard when copying diff's contents" fixes this issue temporarily, so you're spot on! Thanks for this awesome extension.

**Comment by reyronald** [comment]
Great @wuservices ! Glad to hear that. I'll try to include the fix in the next release. And you're welcome :D
