### ISSUE TITLE
Wish to add  issue "Filter" feature, just like JIRA. 

### ISSUE THREAD

**Issue by stonyz** [refined-bitbucket/refined-bitbucket#219]
Wish to add a new feature. User can customized new filters just like JIRA

**Comment by reyronald** [comment]
Hello @stonyz ,

Could you elaborate a little please? I'm not quite sure I understand what the feature would do exactly.

**Comment by stonyz** [comment]
Thanks @reyronald ,  In "Advanced search", we can add a filter to do some complex search. but the filter can be saved. so we have to re-set the same filter when we want to use the save  query condition.  If we can save the filter,  that will be great.
