### ISSUE TITLE
[Feature request] Setting to use DarkTheme 

### ISSUE THREAD

**Issue by puneetar** [refined-bitbucket/refined-bitbucket#223]
Currently Bitbucket allows the use of Dark Theme in the UI. The code diff changes to Dark Theme colors. It would be great if Refined Bitbucket also uses Dark theme when showing colors and in Diffs.

**Comment by reyronald** [comment]
I didn't know that, how do I enable the Dark Theme?

**Comment by puneetar** [comment]
🤦‍♂️ turns out I was using a plugin to do that.

**Comment by reyronald** [comment]
I see. Well in that case I'm going to close this. Thank you for taking the time to drop by and suggest it!

**Comment by johnzhanghua** [comment]
@puneetar  Can I ask what plugin you use for the dark theme? I am looking for it.

**Comment by reyronald** [comment]
@johnzhanghua I don't know what @puneetar used, but I believe you could benefit from [Dark Reader](https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh?hl=en)
