### ISSUE TITLE
Language support: Gherkin/Cucumber (.feature extension)

### ISSUE THREAD

**Issue by alextiley** [refined-bitbucket/refined-bitbucket#231]
Please could you look at the feasibility of adding syntax highlight support for .feature files?

https://docs.cucumber.io/gherkin/reference/

**Comment by reyronald** [comment]
Hello @alextiley, can you submit a pull request? If you can, just add an entry to this file https://github.com/refined-bitbucket/refined-bitbucket/blob/dev/src/syntax-highlight/language-ext.js like this : 

```js
  '.feature': 'language-gherkin',
```

(keep the alphabetical order please!)

**Comment by alextiley** [comment]
@reyronald Thanks for your help - PR is ready. I've manually tested by loading the unpacked extension.

**Comment by reyronald** [comment]
@alextiley Perfect! Thanks for the contribution, it'll be available in the next release.
