### ISSUE TITLE
Seeing ___ERB0___ for ERB within HTML

### ISSUE THREAD

**Issue by wuservices** [refined-bitbucket/refined-bitbucket#234]
Let's say I have code like this in a diff or in a comment,

`<div class="image" style="<%= render(partial: '...') %>">`

What I end up seeing in Bitbucket is

`<div class="image" style="___ERB0___">`

In my code review, I actually asked, what is `___ERB0___` supposed to be? And then they responded with a comment saying they didn't know what was wrong, because it was supposed to say [pasted code]... that then rendered to the same thing with `___ERB0___` again, which is when we realized it was the extension getting confused.

**Comment by reyronald** [comment]
Wow, that's really strange, was that a `.html` file?

**Comment by reyronald** [comment]
I just made a commit with that change to an `.html` file in one of my test repos and I can't reproduce it, can you open it yourself and tell me if you see it there ? https://bitbucket.org/reyronald/tutorial/commits/8b25c6581776ff7851e850d2271e31ad64b9382b

**Comment by wuservices** [comment]
What if you make make a file.html.erb?

**Comment by reyronald** [comment]
It's not going to be picked up by Refined Bitbucket because `.erb` is not a recognized extension for it. Didn't you see that behavior on the commit I linked?

**Comment by oktupol** [comment]
I just had something similar in a `.tpl` file.

Instead of
```
<div class="color-bg" style="background-color: {$color};"></div>
```

Bitbucket showed me
```
<div class="color-bg" style="background-color: ___SMARTY0___;"></div>
```

**Comment by reyronald** [comment]
Is it consistent @oktupol ? Do you see this every time you open that diff ?

**Comment by wuservices** [comment]
@reyronald my problem actually was in a file.html.erb file and did go away without the extension on

I did look at your example and could not reproduce there, but was guessing that it didn't cause an issue due to the lack of erb in the extension combined with html.

**Comment by oktupol** [comment]
@reyronald Yes, I do. I created a small repository to demonstrate this: https://bitbucket.org/cxo-swieland/test/commits/981d8ae201a8c83fc22de4d2d8124c2f87b65e25

**Comment by reyronald** [comment]
@oktupol Thank you so much for the reproduction! It's extremely helpful when trying to isolate the cause of bugs! 🙌 👏 

Apparently this is a flaw on [PrismJS](https://github.com/PrismJS/prism) and would have to be fixed up-stream, not here. I'll keep the issue open though until I get a response from the team.
