### ISSUE TITLE
Can pull requests show if your branches are out of sync with master?

### ISSUE THREAD

**Issue by jonkemp** [refined-bitbucket/refined-bitbucket#235]
On a branch view, Bitbucket shows how many commits the branch is behind master and gives you a link to merge master into the branch. Can the plugin add this for pull requests as well?

**Comment by reyronald** [comment]
This is already added in the PR view by default, but under the "Commits" tab instead of the Overview:

![image](https://user-images.githubusercontent.com/7514993/43324482-38aca19e-9182-11e8-9199-3bfb3527c7a8.png)

Is that what you meant?

**Comment by jonkemp** [comment]
Yes! I didn't know that was there. Thank you.

It would be nice though, if there was some indication on the overview tab.

**Comment by reyronald** [comment]
This could be useful, I'll leave the issue open and explore the possibility of adding it later.

Thanks for the suggestion!

**Comment by reyronald** [comment]
I ended up deciding against this for the moment. I don't want the extension to clutter Bitbucket's UI more than necessary and in this case since the feature is already there natively.

Closing this. If anybody else feels strongly in favor of it though feel free to speak up.

**Comment by sgrimes** [comment]
It seems this now appears on the PR Overview.
