### ISSUE TITLE
Overwriting !important rules

### ISSUE THREAD

**Issue by jestemkarol** [refined-bitbucket/refined-bitbucket#238]
Currently, when we overwrite Bitbucket selectors, user is not able to set his own styles via options. It'd good to have opportunity to change these values somehow.

For example:
```
.refract-container .deletion pre.source {
  background-color: #fff1f2 !important;
}
```

**Comment by reyronald** [comment]
Hello @jestemkarol ,

I'm not sure what you mean. I just tried your selector from the extension and it is working as expected, could you elaborate?

**Comment by jestemkarol** [comment]
This selector comes from the extension [here](https://github.com/refined-bitbucket/refined-bitbucket/blob/cc515494b4767a1d82fc507a42d15db176b8ebb4/src/syntax-highlight/fix.css#L9), if I'm trying to change the colour of diff's deleted line by providing my own selector via options panel, I'm unable to do it, as that selector has `!important` rule to overwrite bitbucket selectors and I don't see any possibility of using my own defined colours for deleted lines other way - or maybe I'm missing some option?

**Comment by reyronald** [comment]
How are you trying to change the color? What selector are you using? Using the same selector we are discussing will work fine. For example, using the custom CSS textarea from the options to include this:

```cs
.refract-container .deletion pre.source {
  background-color: cyan !important;
}
```

Produces:

![image](https://user-images.githubusercontent.com/7514993/43960474-1a183564-9c80-11e8-9fa3-adbea2aeed5f.png)
