### ISSUE TITLE
Undefined number of branches

### ISSUE THREAD

**Issue by gordominossi** [refined-bitbucket/refined-bitbucket#240]
![screen shot 2018-08-14 at 20 16 42](https://user-images.githubusercontent.com/18463025/44124164-1f0447b8-a002-11e8-994a-2d15baa89335.png)

**Comment by samlin86** [comment]
Desktop view:

![branches](https://user-images.githubusercontent.com/24234325/44165315-41cb5180-a07d-11e8-88c5-12c31eebb1df.png)

**Comment by reyronald** [comment]
Thanks for reporting this.

I checked and turns out that Bitbucket's API signature changed. I'll take a look at what to do about it later.

**Comment by reyronald** [comment]
Opened up an issue about in Bitbucket's issue tracker, for reference: https://bitbucket.org/site/master/issues/16993/property-size-missing-in-20-repositories

**Comment by chriswburke** [comment]
@reyronald Would you consider preventing an update if the value is not a number? Happy to create a PR.

**Comment by reyronald** [comment]
@chriswburke Sure! Although I'll still wait for a response from upstream before publishing a new release. This issue is not harming anybody and users can disable it through the options page if they find it too annoying.

**Comment by reyronald** [comment]
Apparently this is already solved upstream by the Bitbucket Staff, so closing this.
