### ISSUE TITLE
Renames are seen as Adds after loading failed diffs

### ISSUE THREAD

**Issue by djdmbrwsk** [refined-bitbucket/refined-bitbucket#249]
Title says it all, renames are seen as Adds after loading failed diffs.  Here's a gif of this in action.
![kapture 2018-09-06 at 13 29 37](https://user-images.githubusercontent.com/886305/45174450-ee11db00-b1d8-11e8-86b9-df8add5caa7b.gif)

**Comment by djdmbrwsk** [comment]
...this might be an issue with Bitbucket 😞

**Comment by reyronald** [comment]
Yup, I think so. Open an issue here: https://bitbucket.org/site/master/issues?status=new&status=open
