### ISSUE TITLE
Can't select some words by double-clicking them when creating/editing comment

### ISSUE THREAD

**Issue by kopach** [refined-bitbucket/refined-bitbucket#250]
**Version**: v3.13.0

**Current behavior:**

1. create/edit comment
2. double click on word in textarea
3. word become deselected
See example:
![select comment](https://user-images.githubusercontent.com/8749624/45213824-faf60380-b298-11e8-8e17-ddcf14c0b751.gif)

**Expected behavior:**

on step `#3` selected word should remind selected

**Comment by reyronald** [comment]
Hey @kopach,

If I remember correctly, this case used to work fine, right?

Just want to figure out if I introduced this bug by mistake or it has always been like this.

**Comment by kopach** [comment]
Hey @reyronald. Not sure actually about this. What I'm definitely sure about - is that it wasn't working correctly in previous version too. I just've been to lazy  to report this 😊

**Comment by reyronald** [comment]
Haha, ok, no worries! I'll look into it, thanks for reporting this! 🙏

**Comment by jwallet** [comment]
working fine on both browser
@andremw this can be close

firefox - Version Dev 76.0b4
![f](https://user-images.githubusercontent.com/23088305/79331037-8a897c80-7ee8-11ea-978e-02db7a599ccf.gif)
chrome - Version 80.0.3987.163
![g](https://user-images.githubusercontent.com/23088305/79331240-dfc58e00-7ee8-11ea-8765-d1cdfbd79581.gif)

**Comment by reyronald** [comment]
Confirmed, Don't know how this got magically fixed. I'll close, thanks for checking @jwallet 

@kopach if you are still seeing this behavior it might require a specific set-up. Let me know here and i'll dive deeper.

**Comment by kopach** [comment]
hey @reyronald. I can confirm, defect isn't reproducible anymore 👍
