### ISSUE TITLE
Integrate with the new beta pull request UI

### ISSUE THREAD

**Issue by alastairtree** [refined-bitbucket/refined-bitbucket#252]
Hello

I love this plugin, thank you for all the hard work. I have noticed that there is a new UI from bitbucket coming, it is currently in beta in the labs https://bitbucket.org/blog/bitbuckets-new-code-review-offers-reviewers-a-fast-track-to-approving-changes.

You can enable the UI:

    1. Click your avatar in the Bitbucket sidebar
    2. Select Bitbucket Labs
    3. Enable the New pull request experience feature

Some features like collapsable panels are now built in whereas others like syntax highlight are still not. Seems like a fair amount of rework will be needed to support the new UI.

**Comment by reyronald** [comment]
Hello @alastairtree,

Yes, I'm aware of the new update that was rolled out. I'm definitely planning to support it as well, and I think this effort would be a great candidate for version 4 of the extension!

**Comment by coagmano** [comment]
If you want to put up a task list for supporting the new UI, I'd be happy to handle a few of the smaller ones

**Comment by LoremFooBar** [comment]
Would love to see this happening! I'd be happy to help as well.

**Comment by spont4e** [comment]
Hello @reyronald 
The new pull request UI is now on by default.
Can you integrate it?

**Comment by reyronald** [comment]
Hey guys! Thank you so much for your interest. Sorry I've been a little absent for a while, but yeah, I'm gonna start integrating this asap feature by feature. Will be releasing them gradually over the next weeks ✌️

**Comment by bguerin** [comment]
The most missing feature for me is the commit message template

**Comment by RIP21** [comment]
Any updates on that? syntax highlighting is heavily missed :(

**Comment by reyronald** [comment]
**v3.19.0** will be up in the store soon with the merge commit template feature working in the new PR experience (cc @bguerin, let me know if it works smoothly for you or if you find any bugs)

@RIP21 Syntax highlighting for the new PR experience will not be implemented here because the Bitbucket team is working to implement it natively themselves and hopefully will land in a few months, so there's no point in doing it ourselves.

If you have any ideas for new features that make sense in the new pull request experience, let me know!

**Comment by bguerin** [comment]
YEAH !! I will test as soon as my plugin get updated

**Comment by bguerin** [comment]
Thanks a lot @reyronald it works perfect !

**Comment by trojkat** [comment]
@reyronald thanks for this update! The merge commit template works great but in a previous version, this template also applied to the squash but it's not working anymore :-(

**Comment by reyronald** [comment]
@trojkat Can you elaborate on what you mean by that? I changed the default merge strategy to Squash and it still works for me

**Comment by brettgoss** [comment]
> Syntax highlighting for the new PR experience will not be implemented here because the Bitbucket team is working to implement it natively themselves and hopefully will land in a few months, so there's no point in doing it ourselves.

@reyronald I think at this point, it's pretty safe to say it's not going to be implemented natively anytime in the near future. Do you have any plans on the horizon to port the syntax highlighting in RefinedBitbucket to the new PR UI? https://jira.atlassian.com/browse/BCLOUD-8673 moved from 'In Progress' back to 'Under Consideration' in June 😞 

Edit: Just found a gist in the comments of the BCLOUD issue that adds stopgap syntax highlighting support using Tampermonkey/Greasemonkey. Using this works for me in the meantime, though I would love to just be able to use RefinedBitbucket without a userscript on top (or just Bitbucket alone for that matter, ha!)
https://gist.github.com/lephuongbg/bf26e0aa24b3c9b0071b7597522ded15

**Comment by adrian861** [comment]
+1 on adding this, Atlassian still has not pulled the trigger.

**Comment by robbieheywood** [comment]
+1 - this would be great!
