### ISSUE TITLE
Links being injected and escaped

### ISSUE THREAD

**Issue by gricey432** [refined-bitbucket/refined-bitbucket#254]
Suddenly I'm having an issue in PR review where email addresses, say in a repo url, are being expanded into html.

Without extension
```
-    def sourceRepo = "git@bitbucket.org:team/package.git"
```
With extension
```
-   def sourceRepo = "<a class="token email-link" href="mailto:git@bitbucket.org">git@bitbucket.org</a>:team/package.git"
```

I'd guess this is related to #245

**Comment by rschev** [comment]
Having the same problem and would like to add:
- The linkification seems to break when the text that looks like a link is surrounded by double quotes (") but not when surrounded by single quotes (')
- It seems overeager in turning text that contains an `@` into a `mailto:` link. For instance, in a *build.gradle* file, you use the `@` to specify the extensions of a dependency. `baseWar "org.group:artifact:1.2.3@war"` does not need to be turned into a `mailto:` link.

**Comment by reyronald** [comment]
Thank you for reporting! I'll take a look and let you know.

**Comment by gricey432** [comment]
Running into more escaping issues now, e.g. the python line
```
+def newRepo = "git@bitbucket.org:team/repo.git"
```
becomes
```
+span class="token keyword">def newRepo = "<a class="token email-link" href="mailto:git@bitbucket.org">git@bitbucket.org</a>:team/repo.git"
```

**Comment by reyronald** [comment]
@gricey432 	@rschev 	Just released an update that will make the linkifying feature optional, so that it doesn't get in the way of you pull request review experience while I look into it further.

Sorry for the inconvenience and thank you for your patience! Will work on this as soon as I have some time.

**Comment by gricey432** [comment]
Cheers!
