### ISSUE TITLE
Syntax highlighting on view file

### ISSUE THREAD

**Issue by psyanite** [refined-bitbucket/refined-bitbucket#255]
Hi, sorry if my query is invalid.

Is it possible to add syntax highlighting when I view file?

Could provide more details if I'm being too vague.

P.S I love you guys, this is amazing you are heroes 💜

**Comment by reyronald** [comment]
Hello @psyanite !

As far as I know the source view already provides syntax highlighting natively, take a look: https://bitbucket.org/atlassian/atlaskit/src/master/package.json.

![image](https://user-images.githubusercontent.com/7514993/46871701-1e641f00-ce00-11e8-84a4-977caf1aee81.png)

Is that what you meant?

**Comment by psyanite** [comment]
I checked on Friday and it looks like it doesn't with kt files. I will double check Monday.

Thanks for the quick response!

**Comment by psyanite** [comment]
Yep, they have it already, except they don't do it on `kt` files. I should file a complaint to them.

Thanks for checking 👍
