### ISSUE TITLE
Hosted bitbucket

### ISSUE THREAD

**Issue by krishnoid** [refined-bitbucket/refined-bitbucket#256]
Does this work (or can it be made to work) on an on-premises Bitbucket installation?   There's nothing in the description that says so one way or the other.

**Comment by reyronald** [comment]
If you mean Bitbucket Server, then there is actually a section in the README that answers that question, here it is:

https://github.com/refined-bitbucket/refined-bitbucket#can-i-use-this-on-bitbucket-server

Cheers!
