### ISSUE TITLE
Code Review features doesn't work on branch compare view

### ISSUE THREAD

**Issue by kopach** [refined-bitbucket/refined-bitbucket#261]
RB Version: 3.14.0

Code review features from #128 doesn't seem to be working on branch compare view.
I do follow [this instruction](https://stackoverflow.com/questions/21437196/how-to-compare-two-revisions-in-bitbucket#31795923) in order to get branch compare view:
`https://bitbucket.org/<OWNER>/<REPO>/branches/compare/<commit-hash>..<commit-hash-older>#diff`

**Comment by reyronald** [comment]
Hey @kopach,

What was implemented in #128 was the branch compare view from the branch detail page. In other words, the screen you see after you go to "Branches" from the sidebar menu and click on a branch, which would be under the URL `https://bitbucket.org/{OWNER}/{REPO}/branch/{BRANCH}?dest={DESTINATION_BRANCH}`. Doesn't that page fulfill your need to compare branches?

Code review features under the URL you specified has never been implemented.

**Comment by kopach** [comment]
Hey @reyronald. Thanks for your response. Feature you've mention is not exactly what I need. On branch compare view - user now able to compare 2 commits, not only existing branches. This becomes super handy if I would like, for example, to group few lasts commits in PR and check what was done there after all.

From branch view (your URL) - go to compare view ([see here](https://bitbucket.org/repo/LboRq/images/792154995-Branches%20%E2%80%94%20Bitbucket%202014-04-05%2021-42-45%202014-04-05%2021-43-23.png)). And on that view - user is allowed to paste commit hash instead of branch name to compare

**Comment by reyronald** [comment]
I see. In that case feel free to open a new issue requesting that screen/page as a new feature.

Will see if I can get around to implementing it this or next week.

**Comment by kopach** [comment]
Cool, thank you man. Have opened new issue here: #262
