### ISSUE TITLE
Notifications that are manually "Marked as Unread" gets removed when removing all issues in another (unrelated) repository

### ISSUE THREAD

**Issue by GGAlanSmithee** [refined-bitbucket/refined-bitbucket#263]
This is what happens visually:

1. #### There are two issues, one from repo 1 (actually unread), one from repo 2 (manually marked as unread)

![image](https://user-images.githubusercontent.com/11805103/48892798-27083600-ee3f-11e8-8d4d-29d6baa174a9.png)

____

2. #### Clicking "mark all {repo} notifications as read" on repo 1
![image](https://user-images.githubusercontent.com/11805103/48892905-65055a00-ee3f-11e8-8f0e-81664c446fb1.png)

____

3. #### All repo 1 notifications are marked as read
![image](https://user-images.githubusercontent.com/11805103/48892949-7cdcde00-ee3f-11e8-81c8-f5f1260f3e3f.png)

____

4. #### The notifications from repo 2 is also marked ass read, but should not be
![image](https://user-images.githubusercontent.com/11805103/48893028-a6960500-ee3f-11e8-8b33-d46234bcc938.png)

____

#### Expected results

Urelated (in another repo) notifications should not be affected 

____

#### Specs

**Browser**: Chrome, Version 70.0.3538.102 
**Refined Github Extension**: Version 18.11.21.1745

**Comment by reyronald** [comment]
Hello @GGAlanSmithee 

There's nothing in this extension that targets that screen or that feature in Bitbucket. This must be a bug in Bitbucket itself or from another extension.

If you can't reproduce this error without this extension enabled then feel free to re-open the issue again and I'll investigate just in case.

**Comment by GGAlanSmithee** [comment]
@reyronald 

I'm sorry but it's only notifications that are manually marked as unread (a feature implemented by this plugin, and not available in vanilla github) that are affected.

I've used github for 5+ years, never seen this even once during these years. I then installed this plugin yesterday specifically for the "mark as unread" feature it provides, and saw ths behaviour immediately. 

I then reproduced it exclusively with issues marked as unread (by this plugin) several times. I then provided very clear reproduction steps with screenshots. Please atleast try to reproduce it before closing this issue as invalid.

____

#### This is the button that I am reffering too, added by refined-github
![image](https://user-images.githubusercontent.com/11805103/48930766-ee299900-eef2-11e8-9950-c6dc834d9170.png)

**Comment by reyronald** [comment]
@GGAlanSmithee You are at the wrong repository, this is Refined Bitbucket, not Refined Github.

Post your issue here: https://github.com/sindresorhus/refined-github

**Comment by GGAlanSmithee** [comment]
🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️  @reyronald I'm so sorry

**Comment by reyronald** [comment]
No problems mate 😆 @GGAlanSmithee
