### ISSUE TITLE
Firefox: 'A script in the extension "Refined Bitbucket" is causing Firefox to slow down'

### ISSUE THREAD

**Issue by Vages** [refined-bitbucket/refined-bitbucket#266]
First of all: I'm not an expert with the Firefox developer tools, so if I'm missing something which could give you a lot more information, please do tell!

I'm on Firefox (64.0) on Mac (10.14.2) with Refined Bitbucket (3.14.1), all the latest versions. The following error message appears on every single pull request that I try to view:

> <img width="691" alt="image" src="https://user-images.githubusercontent.com/3520744/50593666-85dab980-0e99-11e9-856f-fc3830eb9dbf.png">

No amount of waiting seems to help. I have tried 
* disabling all other addons
* opening the developer tools, but the slowdown is so intense that only the network tab is non-blank

… but to no avail.

The slowdown occurs after the initial render of the page. The list of diffs is shown, but the «Load all failed diffs» button is not. My guess is that the block occurs during some initial try at loading all diffs.

Could someone affirm that this is not just my problem? Going to any PR using Firefox with Refined Bitbucket (preferably on a Mac) should do it.  

If it turns out to not just be my problem, I'd be glad to help with further debugging and possibly solving.

**Comment by aki-cat** [comment]
I have this issue too, not just on Firefox, but also on Chrome, in both mac and ubuntu. There seems to be a performance problem overall regarding medium-sized to large PRs.
