### ISSUE TITLE
Feature Request: Description expand/collapse

### ISSUE THREAD

**Issue by nikolasrod** [refined-bitbucket/refined-bitbucket#267]
It would be great to have an option to expand/collapse the pull request description. Sometimes, pull requests related to front-end work can contain a bunch of images, which makes it harder to get to the list of files and go through the changes.

**Comment by reyronald** [comment]
Thank you for your suggestion @nikolasrod 	!

This seems like an easy thing to implement, I'll consider adding this on the next release :)
