### ISSUE TITLE
Disabling the approve and/or merge button if the build is in progress or has failed

### ISSUE THREAD

**Issue by DoWhileGeek** [refined-bitbucket/refined-bitbucket#268]
Atlassian wants a 40% increase in revenue for requiring successful builds? No thanks. How do you folks feel about doing something like this?

**Comment by reyronald** [comment]
😂 😂 

Doesn't this feature already exist though, through merge checks: https://confluence.atlassian.com/bitbucketserver/checks-for-merging-pull-requests-776640039.html ? Isn't that what you had in mind?

**Comment by reyronald** [comment]
I'll close this for lack of response. Feel free to re-open if needed.
