### ISSUE TITLE
Invalid Manifest makes download of extension impossible

### ISSUE THREAD

**Issue by Akaryatrh** [refined-bitbucket/refined-bitbucket#27]
As posted here : https://chrome.google.com/webstore/detail/refined-bitbucket/afppminkfnfngihdocacbgeajbbdklkf/support I wasn't able to download and install your extension either on Chrome 52 or even Canary. The detailed error says "Invalid Manifest".

**Comment by andremw** [comment]
:O Thank you very much and sorry for this inconvenience! I'll check what happened and inform you as soon as I fix it.

**Comment by andremw** [comment]
This was due to a change that I made and passed unnoticed by the web store publishing system. I already reverted it and it will be available within 1 hour. The version will be 2.1.10.

Thanks again!

**Comment by andremw** [comment]
It's already available.
