### ISSUE TITLE
Support keyboard binds for Pull Requests.

### ISSUE THREAD

**Issue by hk0i** [refined-bitbucket/refined-bitbucket#29]
This is that ticket I said I was thinking about filing.
We should support key binds (or key mappings) for certain features.

Here's a short list of what I've come up with:
1. Switching between PR tabs using <kbd>1</kbd>, <kbd>2</kbd>, <kbd>3</kbd>
2. Skipping to next/previous comments in the list using <kbd>N</kbd> and <kbd>P</kbd>

I think the paid version of bitbucket is doing all of this already but it would be a great addition here. I wasn't sure at first how useful the 1, 2, 3 would be then I came up with the idea of N and P.

I have a brief working implementation of both of these actually, and the N/P key bindings I came up with play nicely with the already-provided j and k bindings to scroll up/down to the next/previous items.

I'll try to make a PR for adding it in myself, but as I'm kind of playing round robin with some other things I'm working on I'm going to provide [a gist to my work in progress](https://gist.github.com/hk0i/bef11ec5c0b4edac1fb1c642f0a8a00d).

My only real obstacle is learning how to build/run the plugin and integrate it.
Right now it reads mousetrap from the CDN, but it might be better to pull this dependency into the code base to ensure the right version number to what is written here.

**Comment by andremw** [comment]
Your gist looks really nice, @hk0i! One question: how does it behave when I'm writing a comment and type one of these characters (1, 2, 3, N or P) in the comment?

Regarding the integration with the codebase, I think you can create another folder inside /src and work there.

You'll need to change manifest.json to include the new files. I also think it would be nice if you could keep jQuery out to keep the extension as lightweight as possible. I think you won't have much trouble doing the same things you're doing with jQuery without it. What do you think?

And again, thanks!

**Comment by hk0i** [comment]
Mousetrap takes care of the keybinds for that scenario, if you're typing in a text field the default is to allow text fields to do their thing. If you for some reason wanted it to ignore text fields, there's an option for that, too.

About jQuery, I think you're right. I started with it for some reason, but kind of towards the end I stopped using it as much. As long as chrome supports the JS it should be fine, right?

**Comment by hk0i** [comment]
Oh one more thing. The `self.comments` variable is lazily initialized, this was sort of a work around to wait for the rest of the diff content to load asynchronously but it's still a little error prone.

Since you did the syntax highlighting part maybe you know a better way to wait for the diff content to load?

**Comment by andremw** [comment]
You can take a look at this little helper I wrote: https://github.com/andremw/refined-bitbucket/blob/dev/src/wait-for-render.js

You can use it like this: `waitForRender(diffContentSelector).then(...)`

**Comment by andremw** [comment]
@hk0i actually go ahead and use jQuery if you want to. I'm already using it because of the highlight plugin.. :)

**Comment by hk0i** [comment]
I saw this message, I acknowledged it, but I forgot to reply. I'm going to fork today and play with it for a little bit. Morning coding exercise. I think there's a ticket where someone mentioned they didn't know how to build the plugin. I'm going to dig for that post, unless you have a guide somewhere that says how to build it.

If you don't have a guide somewhere already and I have time, I'll add one on my fork.

**Comment by andremw** [comment]
@hk0i, I updated the README and added a "Contributing" section, where I explain how I'm building the extension.js file and how to load the dev version of the extension in your browser. Let me know if you think it needs more improvement.

**Comment by apitzele** [comment]
@hk0i , one thing to watch out for if you happen to be using Windows is the Browserify commands rely on Unix based wildcards so they choke on Windows (including inside a Cygwin shell).  I started to mess with a library (Glob) that @andremw located which is meant to abstract the wild cards but I didn't make much headway.  If you are coding in Windows, you'll need replace the wild card based expressions with a concatenated list for all the .js files

**Comment by hk0i** [comment]
Thanks for the heads up. I got a little sidetracked this morning so I ended up getting a late start on this. I'm developing on OS X so everything went smoothly so far; I think I'm close to having something _that works_, you guys can review after and let me know what to fix up on this to keep the code consistent.

**Comment by hk0i** [comment]
I'm taking some time to clean this up, so I'll have a more polished version maybe sometime over the next few days and I'll send a PR.

**Comment by andremw** [comment]
PR #31 merged. Thanks, hkoi!
