### ISSUE TITLE
Highlight modal code and collapsed code

### ISSUE THREAD

**Issue by andremw** [refined-bitbucket/refined-bitbucket#3]
All the code that is not loaded by the time the page is rendered is not highlighted.
Two tracked scenarios so far:
- Collapsed code. When clicking "Show more lines" the code doesn't get highlighted.
  ![selection_066](https://cloud.githubusercontent.com/assets/12530242/14460137/336d89c4-0092-11e6-8f25-827ab6e23633.png)
- Old versions of code (modal screen). 
  ![selection_067](https://cloud.githubusercontent.com/assets/12530242/14460176/698fd156-0092-11e6-99c8-6f733a750a70.png)

I think it's just a matter of attaching a event listener for both scenarios and call Prism.highlightAll() again.

**Comment by andremw** [comment]
Just use this selector to get the elements that are not highlighted:
`'.source:not([class*="language"])'`

and use `prism.highlightElement` on each element.

**Comment by andremw** [comment]
Collapsed code highlighting done here https://github.com/andremw/refined-bitbucket/commit/f55dd2868ca06e334667f7f0da8549486b8c1f74

**Comment by reyronald** [comment]
Well, seems like it's resolved! Closing this issue.
