### ISSUE TITLE
Not working in New PR Experience

### ISSUE THREAD

**Issue by timkindberg** [refined-bitbucket/refined-bitbucket#300]
Bitbucket released a new PR refreshed UI maybe 2 months back. I found this plugin and installed it and it seemed to do nothing until I disabled the new experience in my settings. I had to go to the Bitbucket Labs page and toggle off the "New pull request experience". 

![image](https://user-images.githubusercontent.com/168046/61739614-ca0ca900-ad5a-11e9-890f-120cf687cbb3.png)

The new experience is nicer, but still needs help. But it might be a better base to build from for this extension.

Any plans to support it?

**Comment by bguerin** [comment]
Dupe of #252
