### ISSUE TITLE
Merge commit message templates are not applied

### ISSUE THREAD

**Issue by binury** [refined-bitbucket/refined-bitbucket#308]
## Replicate:

- Enable merge commit template
- Supply [gist](https://gist.githubusercontent.com/reyronald/5cb67b555110c4de8c41e7cec43dcc9c/raw/1c399b63cfba1758a31369919793e8ba94091a21/MERGE_COMMIT_TEMPLATE.md)
- Attempt merge
- Observe default message from Bitbucket

## Env:
Chrome | RB 3.18.1

**Comment by binury** [comment]
(Gist linked above is from feature PR author's example)

**Comment by Michaelhobo** [comment]
I'm also seeing this

**Comment by Michaelhobo** [comment]
It sort of looks to me like CORB is blocking Refined Bitbucket from reading commits, pull requests, branches, etc.

Here's some console logs from a pull request page:

main.js:15370 Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at get (main.js:15370)
    at async pullrequestCommitAmount (main.js:17835)
main.js:15370 Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at get (main.js:15370)
    at async getDataToInject (main.js:17328)
    at async Promise.all (/.../...cts-instead/index 1)
    at async mergeCommitMessage (main.js:17313)
get	@	main.js:15370
async function (async)		
mergeCommitMessage	@	main.js:17311
pullrequestRelatedFeatures	@	main.js:17245
init	@	main.js:17100
(anonymous)	@	main.js:17088
Promise.then (async)		
(anonymous)	@	main.js:17082
./src/main.js	@	main.js:17252
__webpack_require__	@	main.js:20
(anonymous)	@	main.js:84
(anonymous)	@	main.js:87
main.js:15370 Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at get (main.js:15370)
    at async Promise.all (/.../…cts-instead/index 0)
    at async addSideBarCounters (main.js:18175)
main.js:15365 Cross-Origin Read Blocking (CORB) blocked cross-origin response https://api.bitbucket.org/2.0/repositories/.../.../pullrequests/.../commits with MIME type application/json. See https://www.chromestatus.com/feature/5629709824032768 for more details.
get	@	main.js:15365
getPullrequestCommits	@	main.js:15359
pullrequestCommitAmount	@	main.js:17835
async function (async)		
pullrequestCommitAmount	@	main.js:17833
pullrequestRelatedFeatures	@	main.js:17241
init	@	main.js:17100
(anonymous)	@	main.js:17088
Promise.then (async)		
(anonymous)	@	main.js:17082
./src/main.js	@	main.js:17252
__webpack_require__	@	main.js:20
(anonymous)	@	main.js:84
(anonymous)	@	main.js:87

It looks like this promise is failing: https://github.com/refined-bitbucket/refined-bitbucket/blob/dev/src/merge-commit-message/merge-commit-message.js#L14

This causes the `if (template && dataToInject)` to always fail.

**Comment by reyronald** [comment]
I haven't looked into this yet but I had another bug report come in this week that happened for that reason @Michaelhobo , but I couldn't reproduce it. Requests were going through fine in my browser instance, so not sure exactly what could be causing this for some folks.

I'll look around this weekend, thanks for the hint!

**Comment by Michaelhobo** [comment]
No problem, please let me know if you need me to reproduce the problem.

I think if you implement this (linked from the chromestatus link in the console logs), it should fix it: https://www.chromium.org/Home/chromium-security/extension-content-script-fetches
