### ISSUE TITLE
Side-bar counters stopped working, error in console

### ISSUE THREAD

**Issue by bgr** [refined-bitbucket/refined-bitbucket#321]
I've been missing the numbers in the side-bar (number of pull-requests, branches, etc.) for about a week now. I tried updating the extension, I'm on 3.18.1 in Chrome 79.0.3945.79.

Console contains the following error:
```
main.js:15370 Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at get (main.js:15370)
    at async Promise.all (/altfuturedoo/dv/pull-requests/index 0)
    at async addSideBarCounters (main.js:18175)
get @ main.js:15370
async function (async)
addSideBarCounters @ main.js:18167
init @ main.js:17124
(anonymous) @ main.js:17088
Promise.then (async)
(anonymous) @ main.js:17082
./src/main.js @ main.js:17252
__webpack_require__ @ main.js:20
(anonymous) @ main.js:84
(anonymous) @ main.js:87
```

Which refers to the line:
```const [branches, pullrequests] = await Promise.all([_api.default.getBranches(), _api.default.getPullrequests()]);```

**Comment by reyronald** [comment]
Hmm weird, I can't reproduce this :S. It works fine for me. Are you logged in when you see this error? Do you get this same error when viewing the pull request list? 

Maybe try uninstalling and re-installing the extension?

**Comment by bgr** [comment]
Yes, I'm logged in. My two colleagues who also use the extension and access the same Bitbucket project don't have the problem (Chrome and Firefox). I tried clearing all Atlassian and Bitbucket related cookies, and I've just tried re-installing, didn't help. I don't have adblock / privacy extensions enabled for Bitbucket.
I'll keep an eye on it and try to debug it some more if I get time.
