### ISSUE TITLE
`approvedByList` merge template section contains `undefined` values

### ISSUE THREAD

**Issue by binury** [refined-bitbucket/refined-bitbucket#323]
The output currently looks like `Approved by: Some User <undefined>`

https://github.com/refined-bitbucket/refined-bitbucket/blob/6afde68a82031457f4e69f2e298f56fe5ff591e6/src/merge-commit-message/merge-commit-message.js#L39-L62

Obviously, that property doesn't exist but I cloned the extension and loaded it to inspect what the user object /does/ have and it appears that there isn't anything like a `username` anymore. Just `nickname` and `display_name`:

```js
{
display_name: "Bin Ury"
uuid: "{ac94f8a1-1153-4ff7-b7dc-d907973e619b}"
links:
self: {href: "https://api.bitbucket.org/2.0/users/%7Bac94f8a1-1153-4ff7-b7dc-d907973e619b%7D"}
html: {href: "https://bitbucket.org/%7Bac94f8a1-1153-4ff7-b7dc-d907973e619b%7D/"}
avatar: {href: "https://avatar-management--avatars.us-west-2.prod.…b4487632/1a3dd9a9-1734-472f-9f20-b81d8c59407b/128"}
__proto__: Object
nickname: "Bin Ury"
type: "user"
account_id: "5a539884409b5e1fb4487632"
}
```

Since the whole `<name>` portion of that exists as a workaround "filler" for the default `<email>` which is unavailable through the API, maybe it would just make the most sense to drop it? 

Side note:
During development, I started getting an error object back from the API, which stopped me from even possibly submitting a pull-request for this issue:
`"Access token expired. Use your refresh token to obtain a new access token."`. How can I handle that? Do I need a local access token? Thanks!

**Comment by reyronald** [comment]
Hey @teddy-error ,

Thank you for finding this and the thorough investigation! Yeah, I'm in favor or dropping it, let's just go with the `display_name`

About the token expired error, can you try logging out / logging back in from Bitbucket after enabling the development extension, and then refreshing your cache? Let me know if that doesn't work for you.
