### ISSUE TITLE
Python triple/multiline quotes not recognised

### ISSUE THREAD

**Issue by RobinvdM** [refined-bitbucket/refined-bitbucket#324]
In Python, triple quotes can be used to make a multiline comment. This is often used in docblocks. They are also mentioned in the [official docs](https://docs.python.org/3/tutorial/introduction.html).

It seems that these quotes are not recognised by the highlighter, as you can see in the image below

![image](https://user-images.githubusercontent.com/1828008/72613141-0e09f080-392f-11ea-94c6-b467c3847794.png)

I'm willing to try to contribute to this project by fixing this error, if someone can point me in the right direction (where can I find the highlighter code, specifically for Python)

**Comment by jwallet** [comment]
rbb uses prism.js
that's their source code for python:
https://github.com/PrismJS/prism/blob/master/components/prism-python.js

maybe you can migrate this issue on their page
