### ISSUE TITLE
Missing plus character in diff (incorrect indentation)

### ISSUE THREAD

**Issue by mnn** [refined-bitbucket/refined-bitbucket#328]
<img width="538" alt="2020-01-29_06-42" src="https://user-images.githubusercontent.com/1975567/73331057-e5ed8c00-4262-11ea-8a97-c8962b887498.png">

I guess the "Don't carry pluses and minuses to clipboard when copying diff's contents" is responsible, because after disabling it, indentation seems fine.

I saw #171, but in that issue it's not a `+`/`-` from diff, but a character from source code.

Chromium 79
Refined Bitbucket 3.19.0

Very nice addon btw :slightly_smiling_face:.

**Comment by jwallet** [comment]
related to #341
