### ISSUE TITLE
Bitbucket compare doesn't work with refined bitbucket enabled

### ISSUE THREAD

**Issue by madskonradsen** [refined-bitbucket/refined-bitbucket#33]

**Comment by andremw** [comment]
Hi @madskonradsen . Thanks for contributing!
I'm not sure what Bitbucket's compare feature is about. Maybe it's not a feature that I use.

Could you clarify, please?

**Comment by madskonradsen** [comment]
It's the feature of comparing two branches on bitbucket. Take this page for example: https://bitbucket.org/chromiumembedded/cef/branches/compare
drop-down number 2 doesn't work when Refined Bitbucket is enabled.

**Comment by przemkow** [comment]
+1

**Comment by reyronald** [comment]
Can anyone confirm if this is still happening? I tested with the link @madskonradsen provided and it seems to be working fine, or maybe I'm not testing the right thing? Let me know

**Comment by andremw** [comment]
I think we can close it. I remember this bug, and it's not happening anymore. It seems that this new UI just "fixed" the bug for us..

**Comment by reyronald** [comment]
Perfect! I'm closing it then
