### ISSUE TITLE
RB decodes encoded HTML entities

### ISSUE THREAD

**Issue by gronostajo** [refined-bitbucket/refined-bitbucket#331]
See this PR: https://bitbucket.org/gronostaj/html-escaping-test/pull-requests/1/expect-bugs-here/diff

The actual 2nd line is:

```
<?= '%7B%7Btest%7D%7D' =>
```

With RB enabled it looks like this:

```
<?= '{{test}}' =>
```

**Comment by jwallet** [comment]
https://github.com/refined-bitbucket/refined-bitbucket/issues/264#issuecomment-449190939

this issue comes from prism.js
https://github.com/PrismJS/prism
maybe you can open an issue on their page as well
