### ISSUE TITLE
Syntax highlighting for Golang not working on new experiencie

### ISSUE THREAD

**Issue by dcu** [refined-bitbucket/refined-bitbucket#333]
In the new PR experience files with .go extension are not highlighted

**Comment by reyronald** [comment]
Syntax highlighting is not implemented for the new experience and won't be, as the Bitbucket teams is working on first-party support that is expected to come in a few months.

**Comment by dcu** [comment]
that's sad, bitbucket team has been saying they're working on syntax highlighting for years and it never happens, that's why I installed this extension. how are you so sure they are going to deliver this time?

**Comment by reyronald** [comment]
I can't say I am "sure" they are going to deliver, but as far as I know it's in their roadmap for the next 4 months.

https://jira.atlassian.com/browse/BCLOUD-8673?focusedCommentId=2361698&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2361698

If they announce they're not going to be delivering this, I'll support it in the extension
