### ISSUE TITLE
 Syntax Highlighter corrupt the display (`%X` is removed)

### ISSUE THREAD

**Issue by ClementMarrast** [refined-bitbucket/refined-bitbucket#335]
Issue found using the plugin to review C code.

The code `%XX` is removed from the display as you can see bellow:
![image](https://user-images.githubusercontent.com/46934374/76075544-80956500-5f9d-11ea-9690-295cb89dd949.png)

You can see it on this PR:
https://bitbucket.org/clement-marrast/test/pull-requests/1/change-print-value/diff

Reproduced on Firefox 73.0.1 under Windows and plugin 3.20.

**Comment by ClementMarrast** [comment]
Update first message with a demo PR.

**Comment by jwallet** [comment]
https://github.com/refined-bitbucket/refined-bitbucket/issues/264#issuecomment-449190939

this issue comes from prism.js
https://github.com/PrismJS/prism
maybe you can open an issue on their page as well
