### ISSUE TITLE
Feature request: Support for hosted Bitbucket solutions

### ISSUE THREAD

**Issue by jarle** [refined-bitbucket/refined-bitbucket#372]
My organization is hosting its own Bitbucket-instance, so the extension is not triggering because of the URL. It would be very useful if it was possible to register custom domains, or have some other mechanism for triggering the extension.

**Comment by jwallet** [comment]
bitbucket server is quite different than the cloud version, some feature won't work because the DOM elements are not the same and pretty much all features are already available with official addons for bitbucket server.

**Comment by reyronald** [comment]
@jarle Bitbucket Cloud and Bitbucket Server are two different products.

This extension is only for Bitbucket Cloud

[Please see this section of the readme for more details](https://github.com/refined-bitbucket/refined-bitbucket#can-i-use-this-on-bitbucket-server)
