### ISSUE TITLE
MERGE_COMMIT_TEMPLATE never applies to first time opening a new PR

### ISSUE THREAD

**Issue by Michaelhobo** [refined-bitbucket/refined-bitbucket#373]
I'm still trying to figure out exactly why this happens. Every time I open a brand new PR from the bitbucket UI, and click "Merge" to bring up the merge dialog, my MERGE_COMMIT_TEMPLATE doesn't apply. After a refresh, it works. I had this behavior on 4 consecutive PRs in a row in quick succession, so I don't think this is some flake or timing related issue.

Has anybody else seen this behavior? I'm using the new Beta PR UI.

**Comment by Michaelhobo** [comment]
I'll add this this is very reproducible. e.g.:
Open the PR UI 30 seconds after creating it? No good.
Opoen the PR UI hours after creating it? Same thing.
Leave the PR UI open for many minutes, and try the Merge button again a few times? Same thing.
After a refresh, it works immediately.

I'm pretty sure there's some bug with the first time opening the PR UI per PR.

**Comment by raijinsetsu** [comment]
We are also experiencing this issue.

When navigating from the bitbucket.org homepage to a PR, clicking Merge: the template is not applied. Clicking Refresh on the browser, then clicking Merge: the template is applied.

The issue appears to be that the extension does not attempt to load the template on page load unless the page is being loaded by a refresh.

Chrome: 85.0.4183.121 (Official Build) (64-bit)
Extension: 3.21.0
BitBucket: New PR experience

No errors reported in the console.

This does work on the old PR experience.

**Comment by reyronald** [comment]
Hey everyone,

I'll look into this this weekend, sorry for the huge delay.
