### ISSUE TITLE
Does not work with "new pull request experience"

### ISSUE THREAD

**Issue by willsheppard** [refined-bitbucket/refined-bitbucket#374]
Syntax highlighting and other features do not work when I am using Bitbucket's new PR display.

It's a shame because this was a wonderful extension before Bitbucket changed their UI.

**Comment by hkennyv** [comment]
+1, happy to contribute to help expedite this if someone can point me in the right direction

**Comment by reyronald** [comment]
Syntax highlighting is intentionally not supported in the new PR experience because the feature is already in the official roadmap of Atlassian for the product, so it wouldn't make sense to work on it, then to have to roll it back,

If the official statement by Atlassian changes then we will act.

**Comment by willsheppard** [comment]
Fair enough. It would be good to mark on the config page which features are not expected to work with the new pull requests though.
