### ISSUE TITLE
New PR UI, padding

### ISSUE THREAD

**Issue by RobertChrist** [refined-bitbucket/refined-bitbucket#377]
Hi @reyronald,

My company is moving from bitbucket server to cloud, and I found this extension in an attempt to make the transition less painful.  One of the issues I have with the new PR UI is that the filetree the new UI displays has so much padding around each element that it only takes a few files before you genuinely can't see all of the files in the tree on a normal monitor any longer.  And once it goes passed the screen, there's no scrollbar available, so its easy to get lost in the filetree.  

I expect the solution is likely to include some sort of scrollbar or scrolling indicator, and give a configuration option to the extension for the amount of padding in the filetree.

I'm not promising I would fix these issues, but if I did, would you consider a PR for them?

**Comment by reyronald** [comment]
Hey @RobertChrist 

Thanks for opening an issue before investing time in a pull request.

This change sounds simple enough for a user script using something like [Tampermonkey](https://www.tampermonkey.net/). Or at the very least, I would try implementing it there before reaching for the extension ecosystem.

Can you give that a shot first?

I'll close for now and let me know when you have anything to report, we can re-open and discuss if we can include it here if you run into any blockers with that approach.

**Comment by RobertChrist** [comment]
Sounds good @reyronald .  I'll play around with it over, and if I find something that I think might work well for a larger audience,  I'll open a new issue with some screenshots.  Thank you for the quick feedback!
