### ISSUE TITLE
Automatic "highlighting" of the selected text - deselects it

### ISSUE THREAD

**Issue by kopach** [refined-bitbucket/refined-bitbucket#38]
I like the feature of automatic "highlighting" of text after selecting it, but most of the times I just want to select the text to copy it. But this feature deselects the text for me, so I have to manually select work by dragging and this is really disappointing. 

As possible solution I see:

- do not deselect the text after double click on it (so, "highlighting"  will work + word becomes selected as expected)
- enable this feature if some key pressed only (e.g. only if double click + ctrl key pressed)

**Comment by reyronald** [comment]
Hey @kopach ,

I totally agree with you, this issue had been bugging me for a while too!

Although the second option would've been the easiest to implement from a technical perspective, I just completed a fix using the first solution instead since I think it's the most natural behavior that a user would expect. I included two gifs of the before and after in the PR, [so feel free to go check them out and let me know what you think](https://github.com/refined-bitbucket/refined-bitbucket/pull/50).

**Comment by kopach** [comment]
hey @reyronald.

From functional perspective - it's exactly what I've expected. Looking forward for new release 🎉 . Thanks.

**Comment by reyronald** [comment]
@kopach Glad to hear that! I'm gonna leave the PR open for a week or so just to give a chance to be reviewed. I'll ping you when the release is ready so you can give further feedback if necessary 8)

**Comment by reyronald** [comment]
Hello @kopach ,

Version 2.6.1 is out with this change! Update your extension, try it out and let me know how it's working for you!

**Comment by kopach** [comment]
Hi @reyronald.
So far - works as expected. Thanks 🎉

**Comment by kopach** [comment]
@reyronald, found an issue looks like related to this feature (cannot revert version to check if it wasn't introduced previously).

So, when I want to select a word written in line commenting text box by double clicking it - this plugin removes selection (means deselects word just after selecting)

**Comment by reyronald** [comment]
@kopach You are absolutely right, I checked and it was introduced with this PR actually, my bad!

The reason being this functionality doesn't highlight occurrences of a word in anything inside a diff block that isn't a line of code, like comments and tasks.

I already have a fix for it which involves extending the highlighting functionality to that type of text as well, I believe the feature can be more useful this way anyway, right?

I'll upload it in the following days, nice catch!
