### ISSUE TITLE
Syntax highlighting doesn't seem to be working?

### ISSUE THREAD

**Issue by pastelsky** [refined-bitbucket/refined-bitbucket#402]
It appears that syntax highlight for the new pull request experience was enabled on  https://github.com/refined-bitbucket/refined-bitbucket/issues/376 

But I don't seem to see it still?

For eg —
https://bitbucket.org/atlassian/atlassian-connect-js/pull-requests/285

![image](https://user-images.githubusercontent.com/8946207/108703598-d78aa600-7530-11eb-9051-708d3cbf35e9.png)

**Comment by reyronald** [comment]
This is how it looks to me

![image](https://user-images.githubusercontent.com/7514993/108719881-7e9e1c00-74f6-11eb-9a9d-feb3ac02f083.png)

Can you tell me which options you have enabled and disabled ?

**Comment by pastelsky** [comment]
@reyronald 
<img width="346" alt="Screenshot 2021-04-05 at 11 37 26 AM" src="https://user-images.githubusercontent.com/8946207/113543111-54667080-9603-11eb-9873-fb5d61899522.png">

**Comment by pastelsky** [comment]
Turned out to be something blocking this extension from working on the page. Closing this.
