### ISSUE TITLE
Feature Request: support for non bitbucket domains (IE: internal BB instances)

### ISSUE THREAD

**Issue by 0x43eba** [refined-bitbucket/refined-bitbucket#413]
My cooperate BB does not match any of the instances of bitbucket in the settings. Can feature be added to allow custom define of bitbucket URL? This is feature I am willing to develop out and submit as PR if wanted.

**Comment by reyronald** [comment]
Are you using Bitbucket Server ?

**Comment by 0x43eba** [comment]
Yes, it would appear that we are.

**Comment by reyronald** [comment]
Bitbucket Cloud and Bitbucket Server are two different products.

This extension is not compatible with Server.

See the README.
