### ISSUE TITLE
Feature Request: keyboard shortcuts for next/previous file in PR review

### ISSUE THREAD

**Issue by davidmankin** [refined-bitbucket/refined-bitbucket#45]
I'd like "j" and "k" to scroll to the next/previous file in the PR review diff view.

**Comment by reyronald** [comment]
Hello @davidmankin !

If I understood correctly, BitBucket already has this featured in their PR view. Both 'j' and 'k' by default will go down and up respectively through iterable elements on the page (file list, comments, patches).

I already tried it myself with different browsers and the extension disabled, and it works. Isn't it what you had in mind?

**Comment by reyronald** [comment]
I'm gonna go ahead and close this issue for now because of what I state above. Feel free to comment if you come back and we can talk about it!
