### ISSUE TITLE
Need new maintainer(s)

### ISSUE THREAD

**Issue by andremw** [refined-bitbucket/refined-bitbucket#46]
Guys, since I no longer use BitBucket, I want to transfer the maintenance to whoever wants to maintain it.

This person needs to have an account at the chrome web store so that I can transfer the extension.

**Comment by reyronald** [comment]
I was just going to ask you that, since there has been some issues popping up and even if we can merge PRs, we can't update the extension at the store. I still use BitBucket everyday so I'm up for the task.

**Comment by andremw** [comment]
Great, @reyronald. I'll need the e-mail of your account in the Chrome Web Store (if you don't have one, you'll need to create).
