### ISSUE TITLE
0 Approvals required to merge Pull request by default

### ISSUE THREAD

**Issue by kopach** [refined-bitbucket/refined-bitbucket#51]
As a user I don't expect that this extension will disable merge button by default. At first, I thought this is some bitbucket bug or I lost some permissions. The same situation happened with my colleagues after I recommended this extension.

How about to set `0` as required amount of approvals by default. So, once user check settings and change this value on something else - it will not be surprise why merge button not working 😄 .

**Comment by kopach** [comment]
Looks like similar issue but different solution: https://github.com/refined-bitbucket/refined-bitbucket/issues/32

**Comment by reyronald** [comment]
Yeah I agree, same thing happened to me the first time.

Actually I think now BitBucket already implemented this feature themselves. 

![image](https://user-images.githubusercontent.com/7514993/30967772-43137346-a42b-11e7-9978-c6c0dfd543d1.png)

I'll test if the functionality is the same/as expected, and if it is, I might just remove it from the extension entirely.

**Comment by reyronald** [comment]
I haven't had the time to test this yet, but just wanted to reach out to @andremw to see if you're ok with me removing the feature from the extension if it turns out that the Bitbucket first-party feature correctly replaces it, just in case, do you have anything to add ?

**Comment by andremw** [comment]
100% ok! :tada:
