### ISSUE TITLE
highlight-ocurrences: Can't select words by double-clicking them when CREATING comment/task

### ISSUE THREAD

**Issue by reyronald** [refined-bitbucket/refined-bitbucket#55]
### Version 2.6.2

Same bug #38 , #52 , but now inside the textarea when creating comments or tasks

**Current behavior:** Double-clicked word inside the textarea of comment or task creation is not selected (actually is selected but inmediately loses it)

**Expected behavior:** Double-clicked word is selected

**Minimal steps to reproduce:**

1. Create a new comment on some code.
2. Add some text in the comment box
3. Double-click on a word

**Comment by reyronald** [comment]
Pull request #56 merged and available in version 2.6.3, already out.

@kopach @GuilloOme

**Comment by kopach** [comment]
hi @reyronald. It works much better now, thanks 🎉 
anyway, some minor improvements still possible 😉 

![select](https://user-images.githubusercontent.com/8749624/31598204-a37086c8-b24c-11e7-93d7-66392784a9f0.gif)
