### ISSUE TITLE
Highlighting disappears when switching tabs

### ISSUE THREAD

**Issue by hk0i** [refined-bitbucket/refined-bitbucket#6]
The syntax highlighting seems to work fine on initial page load, but when switching to the **Commits** or **Activity** tabs the highlighting disappears.

![screen shot 2016-04-12 at 10 49 48 am](https://cloud.githubusercontent.com/assets/755669/14470049/56766da0-009c-11e6-8888-aa1b08977ec4.png)

This might be somehow related to the [Highlight modal code and collapsed code](https://github.com/andremw/refined-bitbucket/issues/3) ticket but I'm not sure exactly.

I took a quick peek at the code and if I can free up some time over the course of the next few weeks I might be able to try and help out.

**Comment by andremw** [comment]
Yep. I'm pretty sure it's related to #3 . The thing is that for each of these events (tab change, show more code etc.) we need to call prism.highlightAll().

Thank you very much!

**Comment by andremw** [comment]
@hk0i , the problem is already solved. You can check by downloading the new version.
