### ISSUE TITLE
Double click removes the highlighted word

### ISSUE THREAD

**Issue by ayamnikov** [refined-bitbucket/refined-bitbucket#64]
Sometimes when I double click on a word it disappears. 

Software versions:
Chrome: Version 51.0.2704.106 unknown (64-bit)
Refined Bitbucket 2.6.4

**Comment by ayamnikov** [comment]
Before double click:

![before-dbl-click](https://user-images.githubusercontent.com/2318230/31943989-3b2f2294-b8d3-11e7-92ea-c7e7c5743c4e.png)

After double click on word "self":

![after-dbl-click](https://user-images.githubusercontent.com/2318230/31944016-51e3c38c-b8d3-11e7-8586-9d8ecb7f50e1.png)

**Comment by ayamnikov** [comment]
I understand how the bug works. It wipes the word out only if it was already highlighted by previous double click.

**Comment by reyronald** [comment]
Thank you for your contribution! I'll take a look at it this week!
