### ISSUE TITLE
Add julia syntax support

### ISSUE THREAD

**Issue by cbecker** [refined-bitbucket/refined-bitbucket#79]
Thanks for this wonderful add on. I'm working with julia files (*.jl), would it be possible to support it?
I saw that prism supports julia highlighting. Is it enough to add the respective line in the `language-ext.js` file?

I am on a slow internet connection for a few weeks which is why I cannot install npm and its tools to have a try. thanks!

**Comment by reyronald** [comment]
Hello @cbecker , thank you for the praise! And yes, that alone should be enough! I'll add it for you since you are having Internet issues, I'll let you know.

**Comment by cbecker** [comment]
@reyronald sounds great, thanks! I'll be happy to test-drive it on my repos

**Comment by cbecker** [comment]
@reyronald what's the best way to try this out?

**Comment by reyronald** [comment]
@cbecker I just published version 3.1.0, which has Julia language support added. Update your extension and let me know!

**Comment by cbecker** [comment]
Thanks, working perfect! it makes a big difference when reviewing code with syntax highlighting :)

**Comment by reyronald** [comment]
@cbecker Definitely! Glad to know you finding it useful :D 

Make sure to try out the rest of the features! =)
