### ISSUE TITLE
Automatically "highlight" ocurrences of the selected text

### ISSUE THREAD

**Issue by andremw** [refined-bitbucket/refined-bitbucket#8]
Just like in everyday IDEs and text editors, we should be able to see all the occurrences of a selected text.

![selection_070](https://cloud.githubusercontent.com/assets/878746/14495183/c703c400-0164-11e6-9a49-86c206c80d20.png)

There must be some good lib already implementing this feature.
If not, it can be implemented by checking the document.getSelection().toString().

This fiddle shows how to capture the highlight "event": http://jsfiddle.net/qY7gE/

**Comment by rproenca** [comment]
Implemented and merged with dev branch.
