### ISSUE TITLE
Hide option conflicts with bitbucket diff tree plugin

### ISSUE THREAD

**Issue by kopach** [refined-bitbucket/refined-bitbucket#84]
I'm using [bitbucket diff tree](https://github.com/minhdam/BitbucketDiffTree)  plugin to show file tree.
And when I use it with `refined-bitbucket` - there are conflicts.

![screenshot at 11-54-50](https://user-images.githubusercontent.com/8749624/33169485-280d1f7a-d045-11e7-9ecf-5cc94b3c9350.png)

**Comment by reyronald** [comment]
Hello @kopach , thanks for the report! From looking at the image I have some idea of where the issue might be, I'll roll out a fix for it some time next week.

I'll also try to add an option to disable the collapse button feature too before that as a temporary "solution" in the mean time.

**Comment by kopach** [comment]
@reyronald. Basically, I really like this option. And this button multiplication is not that big issue for me. Looks ugly, but not the issue. So, personally, I'll not use your temporary solution 😛

**Comment by reyronald** [comment]
Hehe, I see. I won't hurry with the temporary solution then. I still believe though that every feature should be optional though, just in case any user bumps into a similar case in the future.

**Comment by reyronald** [comment]
@kopach v3.2.0 has been released with this fix. Update your extension and let me know of any feedback / issues! :)

**Comment by kopach** [comment]
@reyronald, with this new version the bug seems to be not reproducible anymore.  Thanks 👍
