### ISSUE TITLE
collapse diff button on bottom of the file

### ISSUE THREAD

**Issue by kopach** [refined-bitbucket/refined-bitbucket#88]
Would be great to duplicate collapse diff button on the bottom of the file. Most of the time I'm reviewing files from up to bottom, and if I finalized review for the particular file I want to collapse it. Currently, to do so - I need to scroll up to the beginning of the file. Would be great to have this collapse button on the bottom of the file - to do not scroll back manually to the file beginning just for collapsing.

Under the hood, by clicking collapse button on the bottom of the file I would expect the extension also to scroll the view to the beginning of the file not only collapse it. Otherwise - it could scroll to the wrong place on the page.

**Comment by reyronald** [comment]
That's a great idea! I'm currently working on an undocumented feature right now that my team and myself have been neeeding, as soon as I'm done with that I'll tackle this one.

Thanks for the suggestion, keep 'em coming!

**Comment by reyronald** [comment]
Available in the already published release v3.3.0
