### ISSUE TITLE
[FR] Option to default to "Close source branch" on merge page

### ISSUE THREAD

**Issue by davidmankin** [refined-bitbucket/refined-bitbucket#92]
Much like the default merge strategy, I'd like to be able to always default to have "close source branch" checked in the merge PR screen. (Possibly in the Create and Edit PR pages too.)

**Comment by reyronald** [comment]
Thank you for your suggestion @davidmankin ! I would find that useful too, and it's certainly an easy to add feature. I'll include it in the next release.

**Comment by reyronald** [comment]
Closed via #110 and already available in [version 3.4.0](https://github.com/refined-bitbucket/refined-bitbucket/releases/tag/v3.4.0)

@davidmankin let me know how it goes!
