### ISSUE TITLE
Syntax highlighting interferes with other styles

### ISSUE THREAD

**Issue by l1bbcsg** [refined-bitbucket/refined-bitbucket#93]
This extension adds a cascade stylesheet with styles for syntax highlighter, however css rules in that stylesheet are too generic and interfere with elements outside of code areas that are supposed to be highlighted. One example is inline code produced by backticks (same as this: `code` - not sure how to properly escape it). Naturally it's supposed to look like this:

![screen shot 2017-12-21 at 14 42 58](https://user-images.githubusercontent.com/1044684/34245691-af454390-e65d-11e7-8579-a4e586c7c0ce.png)

Note the faint grey background. 
But with the extension installed and syntax highlighting enabled these pieces of inline code look like this:

![screen shot 2017-12-21 at 14 44 26](https://user-images.githubusercontent.com/1044684/34245690-af2220b8-e65d-11e7-97a6-a8ad96ced2fb.png)

The culprit here is the following rule:
```css
code,tt{background:initial;border:initial}
```
added here: https://github.com/refined-bitbucket/refined-bitbucket/blob/dev/src/syntax-highlight/syntax-highlight.js#L25

Furthermore, this is not event consistent between pages since the style is only added to Diff pull request view and not Activity and the same comment looks differently on those pages. Even the new visual editor is affected: Inside editor window you have the background, but once the comment is posted it's gone.

While the background is really just a minor annoyance, other styles can potentially have bigger impact on styling and layout of other elements.

The solution is probably to explicitly add code area container element to all selectors in that stylesheet. `.udiff-line` might be such selector, but this should be properly looked into.

**Comment by reyronald** [comment]
Hello @l1bbcsg , thank you so much for your thorough investigation of the issue!

I'll try to include this fix in the next release!

**Comment by reyronald** [comment]
This should be solved in the already published release v3.3.0. Let me know!
