### ISSUE TITLE
[FR] Collapse deleted files by default.

### ISSUE THREAD

**Issue by burntcookie90** [refined-bitbucket/refined-bitbucket#96]
Deleted files take a _lot_ of space in the PR view and can usually be collapsed.

**Comment by reyronald** [comment]
Hi @burntcookie90 , thank you for your contribution! Sounds like something that can easily be done, I'll put it on the road-map.

**Comment by reyronald** [comment]
Completed via #101 !

Will be available in next release.

Closing.

**Comment by reyronald** [comment]
Already available in [version 3.4.0](https://github.com/refined-bitbucket/refined-bitbucket/releases/tag/v3.4.0) thanks to @arhughes.

@burntcookie90 let me know how it goes!

**Comment by burntcookie90** [comment]
just updated, already fantastic, thanks @arhughes and @reyronald!
