### ISSUE TITLE
Userscript and Safari extension support?

### ISSUE THREAD

**Issue by legendtang** [refined-bitbucket/refined-bitbucket#98]
I assume that the only feature in this extension is the updater and it is possible to port to any other userscript forms. Do you have any plans on those support?

**Comment by reyronald** [comment]
I'm not sure what you mean when you say the only feature in this extension is the updater, can you elaborate? There are plenty of features packed in this extension. I don't know either to which feature you refer to with "the updater".

Also not sure what you mean with support for Userscripts. If you want to run your own scripts on Bitbucket you can do so by using something like Tampermonkey, I can't see very well what role this extension would play on that.

As for Safari support, that is certainly something I can look into, I'll get back to you in this issue when I get around to it.

**Comment by reyronald** [comment]
I'm going to close this for lack of activity, but feel free to reopen it if you come back!

**Comment by tzimpel** [comment]
I'd be interested in Safari support, too.

**Comment by reyronald** [comment]
Ok @tzimpel , noted, I'll look into it for a future release, thank you for showing interest!

**Comment by steven851007** [comment]
Really cool extension but +1 for safari support!
